bradtraversy/design-resources-for-developers

readme.md
* while seeing the resources i felt that it's little hard to navigate between different contents. it will be easy to navigate if we give an anchor after each contents to navigate back to table of contents.
=> added back to top anchor to navigate easily b/w contents

readme.md
Previous URL for Animate.css was outdated and no longer valid. Updated to current and correct URL.
=> Correct Animate.css URL

readme.md
Fix the wrong link from https://www.invisionapp.com/studio to https://www.darktable.org/
Edit this line with Small Description about new added resource
Link: https://www.darktable.org/
=> [darktable] -> [Downloadable Design Software]

readme.md
XP.css is an extension of 98.css. A CSS library for building interfaces that look like old UIs.
Link: https://botoxparty.github.io/XP.css/
=> [XP.css] -> [CSS Frameworks]

readme.md
SVG Gobbler is a browser extension that hunts down the SVG content in your current tab, highlights unique attributes about it and gives you the option to download, copy to clipboard or export as PNG.
Link:
- https://github.com/rossmoody/svg-gobbler
- [Chrome Web Store](https://chrome.google.com/webstore/detail/svg-gobbler/mpbmflcodadhgafbbakjeahpandgcbch?hl=en-US&authuser=0)
=> [SVG Gobbler] -> [Others]

readme.md
FreebieSketch present in UI Graphics, does not have a valid URL as the URL provided does not resolve `https://freebiesketch.com/`. I suggest we either find a correct URL or remove it altogether.
=> Removed FreebieSketch -> UI Graphics as the URL is not valid

readme.md
Retained the `Illlustrations` -> Vectors & Clip Art and removed the duplicate entry
=> Removed Duplicate of `Illustration.co` from UI Graphics - Duplicate of `Illlustrations` -> Vectors & Clip Art

readme.md
The current URL for PaymentFont `https://paymentfont.com/` does not resolve. Therefore, adding the URL to the corresponding github project.
=> Updated non functioning URL for PaymentFont ->Icon Fonts

readme.md
Vercel UI (Zeit UI) have recently changed it's organization name to Geist UI [due to some copyright issues](https://github.com/geist-org/react/issues/370).
This PR updates the link to it's repository from `https://github.com/zeit-ui/react` → `https://github.com/geist-org/react`.
=> Updated Vercel UI's repository link.

readme.md
Hey maintainer,
This is my to-go place for all finding resources for all my dev needs and scrolling through it I found a minor error in the link to the resource name. So I fixed a bracket error in markdown for a link to the resource name.
I am not adding a new resource so I wasn't sure about the format of PR, apologies if I this isn't the right way.
Thank you for this amazing compilation of resources.
=> [DevDocs] -> [Others] Fixed the error in markdown for resource name

readme.md
Vecta Nano is a Free and Paid SVG compressor tool that uses lossless techniques to compress inefficient SVG codes by removing unnecessary data, resulting in the same image, but large differences in file size.
The Free Option allows converting 10 SVG at one time.
Link: https://vecta.io/nano
=> Vecta Nano -> Image Compression

readme.md
Added Daemonites Material Design For Bootstrap, which is completely free and provides components, that
Material Design Bootstrap charges a fee for.
Link: http://daemonite.github.io/material/
=> [Daemonites Material Design For Bootstrap] ->[UI Components & Kits]

readme.md
Svelte Flat UI link would redirect to subpage instead of homepage
This resource isn't added, the link to it has been updated
Link: https://svelteui.js.org
=> Svelte Flat UI -> Svelte UI Components (UPDATE LINK)

readme.md
On diagnosing a slow-loading Wordpress site, I discovered Fontastic.me, along with their CDN, disappeared without trace in February 2021.
Link: http://fontastic.me
=> Delete [Fontastic.me] -> [Icon Fonts]

readme.md
The Lospec Palette List is a database of palettes for pixel art. We include both palettes that originate from old hardware that could only display a few colors, as well as palettes created by pixel artists specifically for making art. All palettes can be downloaded and imported into your pixelling software of choice.
Link: https://lospec.com/palette-list
=> [Lospec Palette List] -> [Colors]

readme.md
The link to Shorthand CSS was present, but pointed to a dead/spam link
Link: [shorthandcss.com](https://shorthandcss.com/)
=> Shorthand CSS -> Deleted dead/spam link

readme.md
The link to Paletter was present, but pointed to a deadlink
Link: [Paletter](https://www.paletter.app)
=> Paletter -> Removed dead link

readme.md
The link to Retro Vectos was present, but pointed to a dead link
Link: [Retro Vectors](http://retrovectors.com/)
=> Retro Vectors -> Removed dead link

readme.md
The link to Templated.co was present, but pointed to a dead page.
Link: [Templated.co](https://templated.co/)
=> Templated.co -> Deleted dead/spam link

readme.md
The link to Keyframes was present, but pointed to a dead page. No other extension with this name was found.
Link: [Keyframes](https://chrome.google.com/webstore/detail/keyframes/dalaiblmpeklkjnpeocmaojcfldmbfck?hl=en)
=> Keyframes -> Deleted dead link

readme.md
The link to Devicon was present, but pointed to [a dead page](https://konpa.github.io/devicon/), updated the resource's link to the correct one.
Link: [Devicon](https://devicon.dev)
=> Devicon -> Updated link

readme.md
The link to [Material Design Resizer](https://material.io/resources/resizer/) was present, but linked to a dead page. I changed the link to the enclosing [Material Design Resources](https://material.io/resources), which the Resizer used to be a part of.
Link: [Material Design Resources](https://material.io/resources)
=> Material Design Resources -> Others

readme.md
The link to Responsively was present, but linked to a [no longer existing GitHub repo](https://manojvivek.github.io/responsively-app/). Updated the link to point to the app's [landing page](https://responsively.app).
Link: [Responsively](https://responsively.app)
=> Responsively -> Others

readme.md
The link to Match Stick was present, but pointed to a dead page.
Link: [Match Stick](https://matchstick.xyz/)
=> Match Stick -> Deleted dead link

readme.md
The link to FontSpark was present, but pointed to a dead page.
Link: [FontSpark](https://fontspark.app/)
=> FontSpark -> Deleted dead link

readme.md
tsParticles - https://particles.js.org
tsParticles had a broken URL, which was the previous one, updated to the correct one
=> tsParticles -> Fixed tsParticles URL

readme.md
The link used yields a 'non-private' warning in some browsers(e.g. Safari and Firefox); updated the link to use the `www` subdomain, which uses https.
Link: [Freellustrations](https://www.freellustrations.com/)
=> Freellustrations -> UI Graphics

readme.md
Choc Ui was moved from choc-ui.tech to choc-ui.com
=> Update Choc UI site url

readme.md
Recently, links from http://fezvrasta.github.io/bootstrap-material-design/ have been redirected to https://mdbootstrap.com/ so I wanted to update them.
=> MDBootstrap(Fezvrasta) -> UI Components & Kits

readme.md
Hi! Official website of Tabler Icons is https://tabler-icons.io - I'm the autor of Tabler Icons :)  tablericons.com is in no way associated with my project
=> Change url to Tabler Icons

readme.md
The [existing link](https://drawcall.github.io/AniX/) to AniX is no longer working. The repo URL redirects from [drawcall](https://github.com/drawcall/AniX/) to [adajuly](https://github.com/adajuly/AniX).
Link: https://adajuly.github.io/AniX/
=> [AniX] -> [CSS Animations]

readme.md
[shadcn-svelte](https://www.shadcn-svelte.com/) is an unofficial community-led [Svelte](https://svelte.dev/) port of [shadcn/ui](https://ui.shadcn.com/).
Link: https://www.shadcn-svelte.com/
=> [shadcn-svelte] -> [Svelte UI Libraries]

readme.md
Removed DaisyUI from the Frameworks section because it's already in UI Components & Kits which is the correct section.
Link: [https://daisyui.com/](https://daisyui.com/)
=> DaisyUI -> CSS Frameworks [Removed]

readme.md
not sure whether this library is still maintained or not, but the old link is dead, so I modified with github repo link instead
Link: https://github.com/vladotesanovic/ngSemantic
=> update NG Semantic link

readme.md
`[@tsparticles/svelte] -> remove [@tsparticles/svelte]`
@tsparticles/svelte ui library seem no longer available
[Link: @tsparticles/svelte](https://github.com/matteobruni/tsparticles/svelte)
=> @tsparticles/svelte seem no longer available

readme.md
Updated the broken link for Radix Icons. The previous URL (https://icons.modulz.app/) no longer works. Replaced it with the official new URL.
Link: https://www.radix-ui.com/icons
=> Fixed URL for [Radix Icons] -> [Icons]
