bradtraversy/design-resources-for-developers

- readme.md
> Add chakra for react

- readme.md
Adds Wing, Chota, and Picnic css frameworks into the correct section
> CSS Frameworks update

- readme.md
Squoosh - Reduce photo size and convert to modern formats.
Namelix - Generate brandable business names and logos.
> Add Squoosh and Namelix

- readme.md
Add link to new Bootstrap Icons. They're still in Alpha, so I can understand if you don't want to include them yet.
> Add Bootstrap Icons

- readme.md
Very easy and simple online tool to generate maps with data.
> Added MapInSeconds

- readme.md
added 2 new websites for inspiration
Awwards and Codrops
> Add new UI inspiration

- readme.md
Hi,
Added icon-icons.com under icons section.
Kindly accept my PR.
> added icon-icons.com

- readme.md
I've added online Photoshop tool. It's completely free.
> Added online Photoshop editor

- readme.md
Bootswatch has some great themes for Bootstrap! Added under the HTML CSS Templates
> Added Bootswatch resource

- readme.md
I've added Colors & Fonts which have a Collection of Colors, Fonts and Resources for Web Developers & Digital Designers.
> Added Colors and Fonts

- readme.md
Hi, 
I added a couple color palettes generators and a font golden ratio calculator.
> Add Adobe Color, ColorPace and Typography golden ratio

- readme.md
Hey, Brad! I've just added Colorsinspo, a great resource for color palettes, gradients, brand colors and such. Please allow this merge if everything's ok.
> Add Colorsinspo

- readme.md
- Opendoodles
- Illustrations.co
- Fontjoy
- SpinKit
- Moving Letters
> Added resources in UI Graphics, Fonts and CSS Components section

- readme.md
Adding the Polaris design system from Shopify
> Adding Polaris design system

- readme.md
added a valuable grid cheat sheet recourse that I personally use. @bradtraversy
> added grid cheat sheet

- readme.md
NES CSS looks like a 90s video game. Very nostalgic.
> adding NES CSS framework

- readme.md
Hi,
Minor spelling fix.
Kindly accept my PR.
Thanks
> spelling fix

- readme.md
I found few websites like vue-native.io, weex.apache.org
But, I didn't found any suitable category to add.
> Add new features!

- readme.md
Added a Svelte UI section with three entries
> Add Svelte UI section

- readme.md
> adding 98.css framework

- readme.md
Added the W3Schools CSS framework to the CSS Frameworks section
> Add W3.CSS to CSS Frameworks

- readme.md
- update name from 'Colors' to 'Coolors'
- update URL to go straight to color generator
> Change website name and update url

- readme.md
This website is pretty cool when you need a specific width and height image.
> Placeholder.com

- readme.md
Three tools added:
Lunacy: a free design tool that opens .sketch files on Windows and has a full suite of design features.
Smart Upscaler: an AI image upscaler that takes an image and makes it 2-4x bigger.
CSS Layout: a collection of common web layouts and patterns in pure CSS
> Added Lunacy, Smart Upscaler and CSS Layout

- readme.md
pages.xyz is one of the better design galleries, in my opinion: https://www.pages.xyz/
> Add pages.xyz to Design Inspiration

- readme.md
One of the fontjoy resource was deleted.
> Fontjoy added twice

- readme.md
Nice tool to create favicons for multiple platforms.
> Add realfavicongenerator.net to Online Design Tools

- readme.md
Added a reference to an amazing font icon library: Fontisto
> Added Fontisto font icons

- readme.md
Wants to suggest ThemesFor.App in the **HTML CSS Templates** Section. 
**Themes for app** provides free (Do whatever you want), fully-responsive Bootstrap 4 themes for startup and side-project.
> Add: ThemesFor.App in HTML CSS Templates section

- readme.md
Great free clipart, silhouette, coloring pages and drawings that you can use everywhere.
> Adding clipart.email

- readme.md
FlatUIColors has a bunch of amazing colour palettes which will bring light to the UI in different flavours pertaining to the users choice.
> Added FlatUIColors

- readme.md
Added AlyleUI link. These UI components are fantastic, though they're very much same as Angular Material in terms of looking.
> Added AlyleUI

- readme.md
Hi,
Few more additions to the React UI libraries section.
Kindly accept my PR.
Thanks
> Added KendoReact, PrimeReact, Elemental UI

- readme.md
added item to icons category
* added iconmonstr to icons category which is really great place to get icons and embed into website.
see website at [link](https://iconmonstr.com/)
> added iconmonstr to icons category

- readme.md
Image compression from Google Chrome Labs
> Added Squoosh Image compression

- readme.md
Generates favicons and images from Font Awesome icons
> Added FontIcon to Online Design Tools

- readme.md
Sorry, Brad. Fixed missing `|` between link and description.
> Fixed markdown to FontIcon

- readme.md
Avatars as a Sketch library.
Create avatar illustrations in Sketch App with this free library. Combine clothes, hair, emotions, accessories, and colors.
Link: https://avataaars.com/
> free sketch library of avatars illustrations

- readme.md
link of [primer components](https://primer.style/components/)
> added Primer components to react ui/components section

- readme.md
Orbit is a React UI library for travel domain.
> Add Orbit by Kiwi

- readme.md
tinyPNG don't allow to compress JPEG images to compress which is over 5MB with compressJPEG you can do it.
[link of compressJPEG](https://compressjpeg.com/)
> added compressJPEG to image compression category

- readme.md
* **Font flipper** - Preview 800+ Google Fonts on top of your own designs, without having to download the fonts first. You'll play “Hot or Not” to collect fonts you like, and they will be available to download and use.
[link to website](https://fontflipper.com/upload)
> added Font flipper to fonts category.

- readme.md
Fun and Colorful free avatars web generator tool by Fang-Pen Lin using Pablo Stanley sketch library
Link: https://getavataaars.com/
> Fun and Colorful free avatars web generator tool

- readme.md
Add SVGPorn under Icons. 1000+ high-quality SVG logos
> Add https://svgporn.com

- readme.md
[link to website](https://bootstrapmade.com/)
> added bootstrapMade website to html & css templates category

- readme.md
* awesome place to get Premium & Free Bootstrap Templates to build website.
[link](https://bootstraptaste.com/)
> added bootstrapTaste website to html & css templates

- readme.md
> threed.io added

- readme.md
- Ionicons https://ionicons.com/ (Ionic)
- Codicons https://microsoft.github.io/vscode-codicons/dist/codicon.html (Microsoft)
- Material Design icon font http://zavoloklom.github.io/material-design-iconic-font/index.html
> Add Ionicons, Codicons & material icon font

- readme.md
Added InVision Studio to downloadable design software.
> Added InVision Studio

- readme.md
> added lordicon to icon list

- readme.md
> Extract colors into own section

- contributing.md
- Add single resource in one pull request as it will allow for easier review.
- Pull request title should include resource name and resource section.
- Example: `[Tailwind CSS] -> [CSS Frameworks]`
- Provide a link to submitted resource in pull request comment section for easier access without copy paste.
- Example: `Link: https://tailwindcss.com/`
- Double check if the resource is truly free without any kind of hidden surprises.
> Proposal for Contributing Guidelines

- readme.md
Adding San Francisco Fonts. They are free and beautiful.
> San francisco fonts

- readme.md
Open source starter templates and components, a plugins directory and useful tools/utilities to kick start your Tailwind CSS project
Link: https://www.tailwindtoolbox.com/
> [tailwindtoolbox] -> [UI Components & Kits]

- readme.md
Tailwind Starter Kit a beautiful extension for TailwindCSS, Free and Open Source
GitHub Link: https://github.com/creativetimofficial/tailwind-starter-kit
WebSite https://www.creative-tim.com/learning-lab/tailwind-starter-kit/presentation
> [Tailwind Starter Kit] -> [UI Components & Kits]

- readme.md
A free repository for community components using TailwindCSS
Link: https://tailwindcomponents.com/
> [tailwindcomponents] -> [UI Components & Kits]

- readme.md
Color Hunt is a good resource to easily find trendy color palettes.
Link: https://colorhunt.co/
> [Color Hunt] -> [Colors]

- readme.md
Happy Hues is a color palette inspiration site that acts as a real world example as to how the colors could be used in your design projects by Mackenzie Child
Link: https://www.happyhues.co/
> [Happyhues] -> [Colors]

- readme.md
added hint to contributing guidelines to readme.
> added hint to contributing guidelines to readme

- pull_request_template.md
This template will allow users that are not used to contributing to open source projects follow easy pull request guild line and format the Pull request for easier review.
> Added pull_request_template.md

- readme.md
vanilla javascript parallax library: https://github.com/dixonandmoe/rellax
> [Rellax.js] -> [CSS Animations]

- readme.md
> [NG Zorro] -> [Angular UI Libraries]

- readme.md
Removed dublicated elemental ui
> Removed Duplicated - [Elemental UI]

- readme.md
> [LogoHub] -> [Icons]

- readme.md
Make animations on scroll: https://github.com/alexfoxy/laxxx
> [lax.js] -> [CSS Animations]

- readme.md
Link: https://musopen.org/music/
> [Musopen] -> [Stock Music & Sound Effects]

- readme.md
[Web Gradients] -> [Colors]
A cool place to find css gradients
Link: https://webgradients.com/
> [Web Gradients] -> [Colors]

- readme.md
Link: https://saaslandingpage.com/
> [SaaS Landing Page] -> [Design Inspiration]

- readme.md
a JavaScript library for animations: https://github.com/greensock/GSAP
Changed to the official website Link: https://greensock.com/
> [GreenSock] -> [CSS Animations]

- readme.md
I've added Icon Bros to Icons Section.
> [IconBros] -> [Icons]

- readme.md
Gradient Hunt is a free and open platform for color inspiration with thousands of trendy hand-made color gradients
Link: https://gradienthunt.com/
> [Gradient Hunt] -> [Colors]

- readme.md
High resolution web browser logos
Link: https://github.com/alrra/browser-logos#readme
> [Browser Logos] -> [Icons]

- readme.md
Logos for payment systems available in png and svg
Link: https://github.com/mpay24/payment-logos/
> [Payment System Logos] -> [Icons]

- readme.md
> Colormind is a color scheme generator that uses deep learning. It can learn color styles from photographs, movies, and popular art. 
Link: [colormind.io](http://colormind.io)
> [Colormind.io] -> [Colors]

- readme.md
Set of icons representing programming languages, designing & development tools
Link: https://konpa.github.io/devicon/
> [Devicon] -> [Icons]

- readme.md
Break the code barrier
Build better business websites, faster. Without coding.
Link: https://webflow.com/
> [Webflow] -> [Online Design Tools]

- readme.md
> Added javascript animations section

- readme.md
Free of copyrights under CC0 
Link: https://pxhere.com/
> [pxhere] -> [Stock Photos]

- readme.md
https://github.com/mrdoob/three.js/
> [three.js] -> [Javascript Animation Libraries]

- readme.md
I've added Trace which instantly removes the background from your photos.
Link: https://www.stickermule.com/trace
- [ X] I have performed a self-review of submitted resource and its follows the guidelines of the project.
> Added Trace

- readme.md
ColorBox is a free web site to produce color set
https://www.colorbox.io/
> [ColorBox ] -> [ Colors]

- readme.md
A minimal, interactive continuous color palette generator.
Link: [ColorCurves.app](https://colorcurves.app/)
> [ColorCurves.app] -> [Color]

- readme.md
Edit this line with Small Description about new added resource 
Link: https://w3layouts.com/
> [W3Layouts] ->[ Html & CSS Templates ]

- readme.md
A community fork of Semantic-UI
Link: https://fomantic-ui.com/
> [Fomantic-UI] -> [CSS Frameworks]

- readme.md
Base Web provides a robust suite of components out of the box
Link: https://baseweb.design/
> Base Web -> React UI Libraries

- readme.md
A collection of handy, free-to-use tools for web developers, programmers and designers alike.
All tools are free, no sign-up, open-sourced website with the same aim as this repo - bring tools to people!
Link: https://thewebtoolbox.cc/
> [TheWebToolbox.cc] -> [Others]

- readme.md
The name Ant Design was written twice in the readme file.
I have performed a self-review of submitted resource and its follows the guidelines of the project.
> [readme.md -> edit line 430.]

- pull_request_template.md
- readme.md
CompressNow is an online image Compressor which Compress JPEG, GIF and PNG images
Link: https://compressnow.com
> CompressNow -> Image Compression

- readme.md
SweetAlert makes popup messages easy and pretty.
Link : https://sweetalert.js.org/
A beautiful,responsive,customizable,accessible replacement for javascript's popup boxes
Link : https://sweetalert2.github.io/
Reveal Animations When You Scroll.
Link : https://wowjs.uk/
>  Update app config docs

- readme.md
add the link freefrontend for design inspiration section.
LInk: https://freefrontend.com/
> [Freefrontend] -> [Inspiration]

- readme.md
Added Material Design Icons within the icons section.
A icon collection allowing designers and developers targeting various platforms to download icons in the format, color and size they need for any project.
Link: https://materialdesignicons.com/
> [Material Design Icons] -> [Icons]

- readme.md
Turret CSS is a styles framework for development of responsive websites.
Link: https://turretcss.com/
> [Turtle CSS] -> [CSS Frameworks]

- readme.md
UI Gradients color generator
Link: https://uigradients.com
> [UI Gradients] -> [Colors]

- readme.md
[gradienta.io]
A pure CSS and downloadable jpg gradients. 
Link: https://gradienta.io/
> [Gradienta.io] -> [Colors]

- readme.md
JPEG, GIF, PNG Compression
Link: https://compressnow.com/
- [X ] I have performed a self-review of submitted resource and its follows the guidelines of the project.
> Update Image Compression Section

- readme.md
Free Stock Photos with High Resolution
Link: https://www.piqsels.com/
> [Piqsels] -> [Stock Photos]

- readme.md
[Foodiesfeed] [Stock photos]
Foodiesfeed is a photo stock for food photos
Link: www.foodiesfeed.com/
> Added Foodiesfeed to stock Photos

- readme.md
CSS tricks and some unique ideas for beginners and advanced.
> Add in design inspiration

- readme.md
Material Design Resizer
An interactive viewer that helps designers test material design breakpoints across desktop, mobile, and tablet.
Link: https://material.io/resources/resizer/
> [Material Design Resizer] -> [Others]

- readme.md
Discover and be inspired by beautiful webapp designs
Link: https://www.webframe.xyz
> [Webframe] -> [Design Inspiration]

- readme.md
Free Database Designer online
Link: https://app.dbdesigner.net/
> [DB Designer] -> [Online Design Tools]

- pull_request_template.md
- readme.md
#118 [Chocolat.js]
A free lightbox plugin 
Link: http://chocolat.insipi.de/
> [Chocolat.js] -> [A free lightbox plugin]

- readme.md
Best open source admin dashboard & control panel theme
Link: https://adminlte.io
> [ AdminLTE ] -> [UI Components and Kits]

- readme.md
1000+ Material Design palettes
Link: https://material.colorion.co
> [Material Palettes] -> [Colors]

- readme.md
Generate new Color Palette with every spacebar press
Link: https://palettegenerator.colorion.co
> [Palette Generator] -> [Colors]

- readme.md
Swap in replacement of Font Awesome with modern line icons
Link: https://icons8.com/line-awesome
MIT or "Good Boy" License: https://github.com/icons8/line-awesome/blob/master/LICENSE.md
> [Line Awesome] -> [Icons]

- readme.md
Free & Open source photography workflow application and raw developer
Link: https://www.darktable.org/
Original PR is by @KonstantMan
> [Darktable] -> [Downloadable Design Software]

- readme.md
Gradient selector
Link: https://www.grabient.com/
> [Grabient] -> [Colors]

- readme.md
Free Image and Photo Resizer
Link: https://promo.com/tools/image-resizer/
> [Promo Image Resizer] -> [Image Compression]

- readme.md
A set of 8 simple, black & white, stylish illustrations
Link: https://growwwkit.com/illustrations/phonies
> [Growwkit] -> [Vectors & Clip Art]

- readme.md
Free Premium Music for Your Projects 🎁 Royalty Free. Cleared for YouTube.
Link: https://www.unminus.com/
> [Unminus] -> [Stock Music & Sound Effects]

- readme.md
Turn real code into faux code
Link: http://knutsynstad.com/fauxcode/
> [Faux] -> [Online Design Tools]

- readme.md
Create full-fledged web apps visually
Link: https://uibakery.io/
> [Ui Bakery] -> [Online Design Tools]

- readme.md
A little tool for generating shades of any color along with their rgb and hex codes.
Link: https://shadeswash.netlify.app/
> [ShadeSwash] -> [Colors]

- readme.md
Backpack is the Lonely Planet toolset that we use to build front end apps. 
Link: http://lonelyplanet.github.io/backpack-ui/?path=/story/styles--design-tokens
> [Backpack UI] -> [React UI]

- readme.md
Color Space generates color palettes from one color.
Link: https://mycolor.space/
> [ColorSpace] -> [Colors]

- readme.md
Open source design system, guides & components 
Link: https://uilibrary.github.io/done-design-system/
> [Done] -> [Design system]

- readme.md
this site is completely free for create color gradient .
> [CSS gradient] -> [Colors]

- .github/pull_request_template.md
Changes:
- Moved  `pull_request_template.md` to .github folder for better structure.
> Folder structure

- readme.md
2100+ free icons to spice up your creative designs
Link: https://icofont.com/
> [Icofont] -> [Icon Fonts]

- readme.md
890+ handcrafted icons to make your web app awesome. Vectors icons (SVG), JavaScript and font are available.
Link: https://jam-icons.com/
> [Jam Icons] -> [Icon Fonts]

- readme.md
A complete set of 202 thin stroke icons inspired by iOS 7.
Link: https://themes-pixeden.com/font-demos/7-stroke/index.html
> [Stroke 7] -> [Icon Fonts]

- readme.md
Weather Icons is the only icon font with 222 weather themed icons, ready to be dropped right into any project that needs high quality weather, maritime, and meteorological based icons
Link: https://erikflowers.github.io/weather-icons/
> [Weather Icons] -> [Icon Fonts]

- readme.md
A sleek webfont for your favourite payment operators and methods. Featuring 116 icons.
Link: https://paymentfont.com/
> [PaymentFont] -> [Icon Fonts]

- readme.md
Free site where you can create a complete Material Design theme from custom colors
Link: http://mcg.mbitson.com
> [Material Design Theme & Palette Color Generator] -> [Colors]

- readme.md
A set of free premium SVG icons for you to use on your digital products.
Link: https://www.zondicons.com/icons.html
> [Zondicons] -> [Icons]

- readme.md
Free, open source icons from the creators of Tailwind CSS.
Link: https://heroicons.dev/
> [Heroicons] -> [Icons]

- readme.md
Link: https://freebiesketch.com/
> [FreebieSketch] -> [UI Graphics]

- readme.md
Photo Editor from inPixio lets you add a wide range of impressive effects quickly and easily.
Link: https://www.inpixio.com/free-photo-editor/
> [Inpixio Photo Editor] -> [Downloadable Design Software]

- readme.md
given link to contributing.md in readme.md. it will make easier for new contributor to read the contributing guidelines easily without searching for it anywhere.
> added link to contributing.md in readme.md

- readme.md
> [Collect UI] -> [Design Inspiration]

- readme.md
removed duplicate resources #283
> removed duplicate resources

- readme.md
Data visualization library for React based on D3
Link: https://reaviz.io
> [Reaviz] -> [React UI]

- readme.md
Colorate is a color scheme tool for designers and developers. This will help you draw inspiration and serve as a resource for your color work.
Link: https://colorate.azurewebsites.net/
> [Colorate] ->[Colors]

- readme.md
A color tool that makes it easy to lighten and darken colors. It’s perfect for hover states, borders, gradients, and more.
Link: https://www.0to255.com/
> [0to255] -> [Colors]

- readme.md
Browse 5500+ Free Icons. Add any set you wish to easily browse and search its icons.
Link: https://icomoon.io/app/
> [Icomoon] -> [Icons]

- readme.md
**Endless Icons**
[Icons]
A website offering a number of free icons. Icons are tagged and also compressed into kits.
Link: http://endlessicons.com/
> [Endless Icons] -> [Icons]

- readme.md
Largest library of free to use videos, donated by the community
Link: www.pexels.com
> [Pexels] -> [Videos]

- readme.md
Image Optimizer With Quality Options
Link: http://www.imageoptimizer.net/
**Checklist:**
> [Image Optimizer] -> [Image Compression]

- readme.md
Ready to use copy/paste gradient buttons
Link: https://gradientbuttons.colorion.co/
> [Gradient Buttons] -> [Online Design Tools]

- readme.md
Eva Icons is a pack of more than 480 beautifully crafted Open Source icons for common actions and items.
Link: https://akveo.github.io/eva-icons/#/
> [Eva Icons] -> [Icons]

- readme.md
Rive is a real-time interactive design tool that allows you to design, animate, and immediately integrate your assets into any platform
Link: https://rive.app/
> [Rive] -> [UI Graphics]

- readme.md
Reverts bradtraversy/design-resources-for-developers#297
> Revert "[Rive] -> [Online Design Tools]"

- readme.md
There we two entries for Coolors.co. They were slightly different but they were labelled the same and they can both be accessed from the homepage.
> Removed Duplicate Coolors.co

- readme.md
Add unDraw 
Constantly updated Open-source SVG/PNG illustrations that you can use completely free and without attribution
Link: https://undraw.co/illustrations
> Add unDraw.co 

- readme.md
Khroma uses AI to learn which colors you like and creates limitless palettes for you to discover, search, and save.
Link: http://khroma.co/
> [Khroma] -> [Colors]

- readme.md
> [Nodesign.dev] -> [Others]

- readme.md
Link: https://skoda-brand.com/explore-our-brand
> Addded Skoda brand design system 

- readme.md
Really Good Emails
A site offering users a ton of company e-mails from customer service to marketing.
Link: https://reallygoodemails.com/
> [Really Good Emails] -> [Design Inspiration]

- readme.md
A tool that brings attention and understanding to how color contrast can affect different people with visual impairments.
Link: https://whocanuse.com
> [whocanuse] -> [Colors]

- readme.md
This is a very good font website.
Fontello contains about 200+ fonts where you can change the name and the code of the fonts.
Link: www.fontello.com
> [Fontello] -> [Fonts]

- readme.md
A set of 430 crypto and fiat currency icons. Completely free.
Link: http://cryptoicons.co/
> [Cryptoicons] -> [Icons]

- readme.md
Adobe’s design system that provides components and tools to help product teams work more efficiently, and to make Adobe’s applications more cohesive.
Link: https://spectrum.adobe.com/
> [Spectrum] -> [Design Systems & Style Guides]

- readme.md
Kendo React is not a free ressource, #318 
Link: https://www.telerik.com/kendo-react-ui/pricing/
> [Kendo React] -> React UI : Removing Kendo React UI as it is paid

- readme.md
A website to scan websites against WCAG rules. Available as Google Chrome browser extension and as Twitter bot as well.
Link: https://a11ygator.chialab.io/
> [Allygator] -> [Others]

- readme.md
Command line tool to formatted commit messages according to the standards.
Link: http://commitizen.github.io/cz-cli/
> [Commitizen] -> [Others]

- readme.md
A website offering Beautiful, high-res photos of black and brown people.
Link: https://www.nappy.co/
A site offering fonts, mockups, templates graphics and ui kits.
https://freedesignresources.net/
> [Nappy] -> [Stock Photos]

- readme.md
Blush is a free customizable illustration website.
Link: https://blush.design/
- [Y] I have performed a self-review of submitted resource and its follows the guidelines of the project.
> [Blush] - [UI Graphics]

- readme.md
Tool For Code Foramtter,Minifier,File Converter.
Link:- https://www.cleancss.com/
Checklist:
> [CleanCSS]-> [Others]

- readme.md
Added an amazing blog called [Webdevtrick](https://webdevtrick.com/).
> Added Webdevtrick

- readme.md
A suite of React components, sensible UI design, and a friendly development experience.
Link:  https://rsuitejs.com/en/
> added react suite ui

- readme.md
The fontello was on the bad place. Sorry for that.
Link: www.fontello.com
> Move fontello from fonts to icon fonts.

- readme.md
Create your custom icon fonts in seconds. Over 9,000 icons available to pick from or upload your custom svg
Link: http://fontastic.me/
> [Fontastic.me] -> [Icon Fonts]

- readme.md
Stock Videos - Pixabay Videos
Pixabay is like Pexels, it has stock photos and videos.
Link: https://pixabay.com/videos/
> [Pixabay Videos] - [Stock Videos]

- readme.md
Unique, worry-free model photos
Enhance your creative works with photos generated completely by AI. Find model images through our sorted and tagged app, or integrate images via API.
Link: https://generated.photos/
> [Generated Photos] -> [Stock Photos]

- readme.md
[Unscreen] -> [Online Design Tools]
Unscreen
Remove Video Background, 100% Automatically and Free
Link: https://www.unscreen.com/
> [Unscreen] -> [Online Design Tools]

- readme.md
[Colorable] -> [Colors]
Take a set color palette and get contrast values for every possible combination – 
useful for finding safe color combinations with predefined colors and includes pass/fail scores for the WCAG accessibility guidelines.
Link: https://colorable.jxnblk.com/
> [Colorable] -> [Colors]

- readme.md
[Fonts Arena] -> [Fonts]
FontsArena is a curated typography website with a focus on contemporary typography and high quality free fonts.
Link: https://fontsarena.com/
> [Fonts Arena] -> [Fonts]

- readme.md
Official Google Material Color Tool
Link: https://material.io/resources/color
> [Google Material Color Tool] -> [Colors]

- readme.md
`[SVGminify] -> [Image Compression]`
This tool removes superfluous information, thereby reducing the size of your SVG files.
Link: https://www.svgminify.com/
> [SVGminify] -> [Image Compression]

- readme.md
siteInspire is a showcase of the finest web and interactive design.
Link: https://www.siteinspire.com/
> [Site Inspire] -> [Design Inspiration]

- readme.md
[Ikonate] -> [Icons]
Fully customisable & accessible vector icons
Link: https://ikonate.com/
> [Ikonate] -> [Icons]

- readme.md
[Befonts] -> [Fonts]
High quality fonts free for personal or commercial use. With beautiful script type, professional sans serif font and more.
Link: https://befonts.com/
> [Befonts] -> [Fonts]

- readme.md
Velocity.js
Velocity is an animation engine with the same API as jQuery's $.animate(). It works with and without jQuery. It's incredibly fast, and it features color animation, transforms, loops, easings, SVG support, and scrolling.
Link: http://velocityjs.org/
> [Velocity.js]  ->[Javascript Animation Libraries]

- readme.md
A simple tool to get the hex code along with the color name from any image.
Link: https://colorhexpicker.com
> [Color Hex Picker] -> [Colors]

- readme.md
Quickly generate  App Icons in different sizes for your iOS  macOS Android Mobile Apps projects
Link: https://appicon.co/
> [appicon] -> [Uncategorized Stuff]

- readme.md
Just an attempt to give a look to this repository 😅
> Added images

- readme.md
A tiny requestAnimationFrame powered 60+fps
lightweight parallax hover tilt effect for jQuery.
Link: http://gijsroge.github.io/tilt.js/
> [Tilt.js]->[Javascript Animations]

- readme.md
Quasar and Vuetify are now #1 and #2 in popularity in the Vue community.  Just wanted to draw attention to the fact that Quasar is MD and offers more than just UI components as it allows you to create a single app that deploys on all platforms.
Revised description ..
"High-performance Material Design component suite with builders for SPA, SSR, PWA, Mobile (Cordova & Capacitor), Desktop (Electron) and Browser extensions"
Link: https://quasar.dev
> [Quasar] -> [Vue UI]

- readme.md
100% free mockups for all devices
Link: https://mockuphone.com/
> [ Mockuphone ] -> [Product & Image Mockups]

- readme.md
Convert your source code into nice pictures for your articles, tweets, messages, posts...
Link: https://www.kodeshot.net
> [ Kodeshot ] -> [ Online Design Tools ]

- readme.md
2000+ Essential LineIcons for Designers and Developers
Link: https://lineicons.com/
- [yes ] I have performed a self-review of submitted resource and its follows the guidelines of the project.
> [LineIcons] -> [Icons]

- readme.md
Arabic Fonts
The most used website for arabic fonts , do to arabic font rarity this website will help alot
Link: https://arabicfonts.net/
[ YES] I have performed a self-review of submitted resource and its follows the guidelines of the project.
> [Arabic Fonts] -> [Fonts]

- readme.md
Linear Icons has both a free and premium tier. The change will automatically link to the free icons.
> [Linear Icons] -> [Icons]

- readme.md
Added free icon site : uxwing.com
Well optimized, Free SVG and PNG Icons for commercial use without attribution 
Link: https://uxwing.com/
> [UXWing] -> [Icons]

- readme.md
Linea: Featuring 750+ Free Icons
Link: https://linea.io/
> [Linea] -> [Icon Fonts]

- readme.md
A collection of repeatable SVG background patterns for you to use on your web projects.
Link: http://www.heropatterns.com/
> [Hero Patterns] -> [UI Graphics]

- readme.md
New site under "UI Components & Kits"
Useful Bootstrap 4, HTML5, CSS3 Code Snippets to Build Web Layouts
Link: https://tagfold.com/
> Update "UI Components & Kits" readme.md

- readme.md
A composable charting library built on React components
Link: http://recharts.org/en-US/
> [Recharts] -> [React UI Libraries]

- readme.md
Link: https://tiny-helpers.dev/
Edit this line with Small Description about new added resource
Link: www.linkToResource
> [Tiny helpers] -> [Others]

- readme.md
Paletton.com is a designer color tool designed for creating color combinations that work together well.
Link: https://paletton.com
> Added a color designer website.

- readme.md
Ready-to-use Tailwind CSS components/blocks.
Link: https://mertjf.github.io/tailblocks/
> [tailblocks] -> [UI Components & Kits]

- readme.md
Toolplate is a free collection of HTML/CSS templates place.
Link: https://www.tooplate.com/
> [Toolplate] -> [HTML & CSS Templates]

- readme.md
Add Brand Colors Resource to Colors Section
> Add Brand Colors Resource

- readme.md
This generator will assist in creating a pure CSS corner ribbon.
Link: https://www.cssportal.com/css-ribbon-generator/
> [CSS Ribbon Generator] -> [Others]

- readme.md
> [Wix] -> [Online Design Tools]

- readme.md
A site for web design inspiration, updated daily.
Link: https://www.webdesign-inspiration.com/
> [Web Design Inspiration] -> [Design Inspiration]

- readme.md
Front CSS Framework
Link: https://framework7.io/
- [X ] I have performed a self-review of submitted resource and its follows the guidelines of the project.
> [Framework7] -> [CSS Frameworks]

- readme.md
Download vector logos of brands you love
Link: https://worldvectorlogo.com/
> [World Vector Logo] -> [Vectors & Clip Art]

- readme.md
Free landing page templates for startups.
Link: https://grayic.com/shade/
> [Shade] -> [HTML & CSS Templates]

- readme.md
Fully coded HTML templates to help you easily build your startup landing page without hassles.
Link: https://cruip.com/free-templates/
> [Cruip] -> [HTML & CSS Templates]

- readme.md
Check cross-browser compatibility of frontend technologies.
Link: https://caniuse.com/
> [Can I Use] -> [Others]

- readme.md
Check JavaScript versions (ES5, ES6, ES2016+ etc.) compatibility across different compilers, servers/runtimes and platforms (Desktop and Mobile).
Link: https://kangax.github.io/compat-table/es6/
> [kangax-js-compat-table] -> [Others]

- readme.md
Very famous website to build, test and discover frontend code.
Link: https://codepen.io/
> [Codepen] -> [Others]

- readme.md
Add Instant Logo Search resource for brand logo icons
Add Gratisography resource for stock images
> Add Icon resource  & Stock Images resource

- readme.md
Adding Loading.io resource
Adding Epic Spinners resource
> Add UI Components & Kits resources

- readme.md
add get waves resource for free SVG wave generator to make unique SVG waves for web design in online design tools section
> Add get waves resource

- readme.md
Add Clippy resource for easy CSS clip-path maker in online tools section
> Add Clippy resource

- readme.md
use eight values specifying border-radius in CSS
Link: https://9elements.github.io/fancy-border-radius/full-control.html
> Add Fancy Border Radius

- readme.md
GTmetrix	is Website Speed and Performance Optimization
> Add GTmetrix resource

- readme.md
ColorZilla - A powerful online photoshop like CSS gradient editor.
Responsively - A tool that enables designers to debug their apps with ease, cross-platform
Link:https://www.colorzilla.com/
Link:https://manojvivek.github.io/responsively-app/
> [Colorzilla] -> [Colors], [Responsively] -> [Others]

- readme.md
NavNav Website contains many  examples of navbars to get inspire
> Add NavNav Website

- .github/pull_request_template.md
- readme.md
A css flexbox cheatsheet to reference when using flexbox
Link: http://flexbox.malven.co/
> [Flex Malven] -> [Online Design Tools]

- readme.md
The Best Landing Page Design Inspiration
Link: https://www.lapa.ninja/
> updated design inspiration

- readme.md
Vue UI kit featuring a modern design system with dozens of custom components based on bootstrap 4.
https://designrevision.com/downloads/shards-vue/
> vue ui contribution

- readme.md
A great free online tool for resizing and compressing photos and images for displaying on the web.
Link: http://jpeg-optimizer.com/
> [JPEG Optimizer] -> [Image Compression]

- readme.md
A community for designers to share & download transparent background PNG cliparts
Link: https://www.hiclipart.com/
> Add HiClipart under Vectors & Clip Art

- readme.md
Link: https://ekoopmans.github.io/html2pdf.js/
> [html2pdf.js] => [Others]

- readme.md
🎨 Palette List is the simplest way to generate color palettes for designers, developers and marketeers. You pick 2 colors you like (i.e. Red and black) and the tool generates thousands of palettes for you. You can also download the palettes! 💥
Link: https://www.palettelist.com/
> [Palette List] -> [Colors]

- readme.md
[Image Color Picker] -> [Colors]
Resource Name - Image Color Picker
Image color picker and palette genertor
Link: https://image-color.com
> [Image Color Picker] -> [Colors]

- readme.md
The two descriptions were mixed up. 
Link: http://flexbox.malven.co/
> [Grid Malven] [Flex Malven] -> [Online Design Tools]

- readme.md
[FontDrop] -> [Fonts]
Resource Name - FontDrop
Simple and easy way to view the contents of font files.
Link: https://fontdrop.info
> [FontDrop] -> [Fonts]

- readme.md
Link: https://github.com/zeit-ui/react
> [Vercel UI] -> [React UI]

- readme.md
A set of framework-agnostic web components based on neumorphic design.
Link: https://soft-components-docs.web.app/
> [Soft Components] -> [UI Components & Kits]

- readme.md
Free Landing Page Templates and Bootstrap Themes
Link: https://uideck.com/
> [UIdeck] -> [HTML & CSS Templates]

- readme.md
Colorpicker is a free and open-source color application. You can pick any color on your screen, manipulating it and storing it in Colorpicker. It's available on Windows, OSX and Linux!
Website: [https://colorpicker.fr](https://colorpicker.fr)
Github: [https://github.com/Toinane/colorpicker](https://github.com/Toinane/colorpicker)
> [Colorpicker] -> [Downloadable Design Software]

- readme.md
Resource from #410 
A pure CSS tooltip library for your lovely websites
Link: https://kushagra.dev/lab/hint/
> [Hint.css] -> [CSS Frameworks]

- readme.md
#410 
Pure CSS Image Hover Effect Library
Link: http://imagehover.io/
> [imagehover.io] -> [CSS Frameworks]

- readme.md
#410 
a minimal, responsive, style-agnostic CSS framework
Link: https://minicss.org/
> [mini.css] -> [CSS Frameworks]

- readme.md
A graphical user interface for creating custom CSS keyframe animations
Link: https://keyframes.app/
> [Keyframes.app] -> [CSS Animations]

- readme.md
A collection of free and customizable vector illustrations
Link: https://stories.freepik.com/
> [Stories by Freepik] -> [Vectors & Clip Art]

- readme.md
A collection of free illustrations and more
Link: https://delesign.com/free-designs/graphics
> [Delesign] -> [Vectors & Clip Art]

- readme.md
A small JavaScript library to create and animate annotations on a web page
Link: https://roughnotation.com/
> [roughnotation] -> [Javascript Animation Libraries]

- readme.md
Added IRA design to UI Graphics section.
Link: https://iradesign.io/
> [IRA Design] -> [UI Graphics]

- readme.md
A subset of Storytale free quality illustrations
Link: https://storytale.io/freebies/
> [storytale.io] -> [UI Graphics]

- readme.md
In my free time, I create free web templates and share them on my web app so everybody could use them. At this moment there are only 6 themes, however, I try to add something new every week. In the future, I will also work towards adding other resources like illustrations, icons, etc. 
Link: www.splawr.com
> [Splawr] -> [HTML & CSS Templates]

- readme.md
Evericons is a big pack of over 460 free icons designed by Aleksey Popov.
Link: https://www.figma.com/resources/assets/evericons-for-figma/
> [Evericons] -> [Icons]

- readme.md
Create fast loading, highly readable, and 100% responsive interfaces with as little css as possible.
Link: https://tachyons.io/
> [Tachyons] -> [CSS Frameworks]

- readme.md
I think HTML Color Codes deserve to be in this list and is a good com
HTML Color Codes
Edit this line with Small Description about new added resourceGet HTML color codes, Hex color codes, RGB and HSL values with our color picker, color chart and HTML color names.
https://htmlcolorcodes.com/
> [HTML Color Codes]-> readme.md

- readme.md
FREE platform for curated open-source typefaces.
Link: https://open-foundry.com/
> [Open Foundry] -> [Fonts]

- readme.md
[Glyphter] -> [Fonts]
Turns SVG icons into font files. Usefull if you want a custom library that has only the icons you want.  
Very easy to use. Just drag n drop.
The result is smaller file sizes aswell since you only load icons you want.
Link: https://glyphter.com
- [Y] I have performed a self-review of submitted resource and its follows the guidelines of the project.
> [Glyphter] -> [Fonts]

- readme.md
it will show all the color schemes which are popular and how many people are interested in .
Link: https://www.colourlovers.com/palettes
it is a framework build on bootstrap with material style
Link: https://fezvrasta.github.io/bootstrap-material-design/
> [colour Lovers] -> [colors] & [material bootstrap] -> [css frameworks]

- readme.md
Call to Idea is a collection of different web elements including 404 pages, logins, pricing tablesm, navbars, sliders, profile pages etc.
https://www.calltoidea.com/
> Add Calltoidea to design inspiration

- readme.md
#[Prime Vue] -> [Vue UI]
PrimeVue is a rich set of open-source native components for Vue.
Link: https://www.primefaces.org/primevue/
> added a vue library

- readme.md
Add `SVG Repo` to the `Icons` section
Explore, search and find the best fitting icons or vectors for your projects using wide variety vector library. Download free SVG Vectors for commercial use.
Link: https://www.svgrepo.com/
> `SVG Repo -> Icons`

- readme.md
Free online Color (USA) or Colour (British) tools: information, gradient generator, color wheels etc.
Link: https://www.htmlcsscolor.com/
It gets HTML color codes, Hex color codes, RGB and HSL values with our color picker, color chart and HTML color names.
Link: https://hexcolorcodes.org/
Generate critical css for your web pages
Link: https://www.sitelocity.com/critical-path-css-generator
- [/ ] I have performed a self-review of submitted resource and its follows the guidelines of the project.
> [HTML CSS Color, HEX Color Codes, Critical Path CSS Generator] -> [Colors Section and Others]

- readme.md
Convert PNG files to SVG online & free. (One of the services provided by it.)
Link: https://convertio.co/png-svg/
> `Convertio -> Icons`

- readme.md
**Title:** Muzli Search
**Description:** A search engine for design inspiration
**Link:** https://search.muz.li
> [Muzli Search] -> [Design Inspiration]

- readme.md
Easily generate avatars for your projects with Big Heads by Robert Broersma.
Link: https://github.com/RobertBroersma/bigheads
> [Big Heads] -> [Online Design Tools]

- readme.md
Framer Motion is an open source React library to create powerful animations.
Link: https://www.framer.com/motion/
> [Framer Motion] -> [React UI]

- readme.md
Online animated GIF maker and Image Editor, including Image Optimization and supports WebP conversion.
Link: https://ezgif.com/
> [EZGif] -> [Image Compression]

- readme.md
Link: https://www.iviewui.com/
> [View UI] -> [Vue UI]

- readme.md
Resource Name - React Spectrum
React Spectrum is a React implementation of Spectrum, Adobe's design system. It provides components that are adaptive to interactions and screen sizes across devices, and includes full screen reader and keyboard navigation support for accessibility.
Link: https://react-spectrum.adobe.com/react-spectrum/index.html
> [React Spectrum] -> [React UI]

- readme.md
Resource Name - Custom Shape Dividers
Free tool to make it easier for designers and developers to export a beautiful SVG shape divider
Link: https://www.shapedivider.app/
> [Custom Shape Dividers] -> [Vectors & Clip Art]

- readme.md
Free vector illustrations to class up your project
Link: https://icons8.com/illustrations
> [icons8/illustrations] -> [UI Graphics]

- readme.md
A lightweight JavaScript library for creating particles
Link: https://vincentgarreau.com/particles.js
> [Particles.js] -> [Javascript Animation Libraries]

- readme.md
The motion graphics toolbelt for the web
Link: https://mojs.github.io/
> [mo.js] -> [Javascript Animation Libraries]

- readme.md
Open Doodles is currently listed twice under one resource section.
> Removed duplicate [OpenDoodles] -> [UI Graphics]

- readme.md
Replaced the obsolete `particles.js` with the new `tsParticles` and added all the components to their own frameworks
`particles.js` is an obsolete and abandoned library with many unsolved bugs and issues. `tsParticles` is a library born from it with all these bugs and issues solved, less CPU used and many new features
Link: https://particles.matteobruni.it/
> [tsParticles] -> Added tsparticles, react-tsparticles, particles.vue, ng-particles and svelte-particles

- readme.md
CoolHue 2.0 showcases many examples of gradients that people can use in their websites. The gradients can be copied and pasted in CSS format or downloaded in PNG format. 
Link: (https://webkul.github.io/coolhue/)[https://webkul.github.io/coolhue/]
> [CoolHue 2.0] -> [Colors]

- readme.md
Download High quality free images in different sizes.
Link: https://www.freeimages.com/
> [Freeimages] -> [Stock Photos]

- readme.md
Icon set made with pure css code, no dependencies, "grab and go" icons
Link: https://cssicon.space/
> [CSS ICON] -> [Icons]

- readme.md
Free seamless pattern maker
Link: https://patternico.com
> [Patternico] -> [UI Graphics]

- readme.md
Create beautiful browser & mobile mockups in seconds
Link: https://screenshot.rocks/
> [Screenshot.rocks] -> [Product & Image Mockups]

- readme.md
Free background Images for awesome Landing Pages
Link: https://freellustrations.com/
> [Freellustrations] -> [UI Graphics]

- readme.md
CSS Framework #494 
Link: https://ivory-ui.web.app/
> [Ivory] -> [CSS Frameworks]

- readme.md
Free To Use Cinemagraphs Created With VIMAGE App
Link: http://stock.loopvidz.com/
> [Loopvidz] -> [Stock Videos]

- readme.md
Build consistent, themeable React apps based on constraint-based design principles.
Link: https://theme-ui.com/home
> [Theme UI] -> [React UI]

- readme.md
Crafting a language that transcends all borders
Link: https://asphalt.gojek.io/
> [Asphalt] -> [Design Systems & Style Guides]

- readme.md
Create social media banner designs in minutes from hundreds of customizable templates.
Link: https://www.taler.app/
>  [Taler] -> [Online Design Tools]

- readme.md
Free online diagram editor tool.
Link: https://www.draw.io/
> [Draw.io] -> [Online Design Tools]

- readme.md
Device Shots is a free small web application that helps you create high-resolution device mockups for social media, for free.
Link: https://deviceshots.com/
> [Device Shots] -> [Product & Image Mockups]

- readme.md
Very useful collection of snippets and code examples for a variety of languages and frameworks.
Link: https://shortcode.dev/
> [shortcode.dev] -> [Uncategorized]

- readme.md
One library, over 40,000 vector icons. Modern replacement for icon fonts. Fast, easy to use.
Link: https://iconify.design/
> [Unified icons] -> [Icons]

- readme.md
> [Laws of UX] -> [Design Systems & Style Guides]

- readme.md
Fast is an interface system that can be used with modern Web Frameworks such as React, Vue and Angular.
Link: https://www.fast.design/
> [Fast] -> [UI Components & Kits]

- readme.md
Free animated illustrations
Link: https://www.pixeltrue.com/illustrations
> [Pixeltrue Illustrations] -> [UI Graphics]

- readme.md
Resize png without losing transparent background.
Link: https://onlinepngtools.com/resize-png
> [Onlinepngtools] -> [Image Compression]

- readme.md
Bumbag is a friendly React UI Kit suitable for MVPs or large-scale applications.
Link: https://bumbag.style/
> [Bumbag] -> [React UI]

- readme.md
Link:- https://playcode.io/
Javascript playground.
> [PlayCode] >> [Others]

- readme.md
Lorem Picsum is an easy to use API to get beautiful placeholder images. Size and other parameters can be specified.
Link: https://picsum.photos/
> [Lorem Picsum] -> [Stock Photos]

- readme.md
Halfmoon UI is a responsive and lightweight framework, designed for quickly building beautiful dashboards and product pages.
Link: https://www.gethalfmoon.com/
> [Halfmoon UI] -> [CSS Frameworks]

- readme.md
Particle-bg
A React particles animation background component
Link: https://github.com/lindelof/particles-bg
- [] I have performed a self-review of submitted resource and its follows the guidelines of the project.
> add particles bg

- readme.md
A useful HTML cheatsheet with a brief explanation and examples for every HTML tag.
Link: https://allthetags.com/
> [All The Tags] -> [Others]

- readme.md
Free nature images
Link: http://www.freenatureimages.eu
> Saxifraga -> Stock Photos

- readme.md
Free clip art you can use for anything you like
Link: http://www.clker.com
> Clker -> Vectors & Clipart

- readme.md
Free access to 370 million pieces of art
Link: https://www.deviantart.com
> DeviantArt -> Design Inspiration

- readme.md
Free images to provide scientists, resource managers, government agencies, community groups and graphics professionals with a resource for enhancing science communication.
Link: https://ian.umces.edu/imagelibrary
> Integration & Application Network Image Library -> Stock Photos

- readme.md
3000 free medical images to illustrate your publications and Powerpoint presentations
Link: https://smart.servier.com
> Servier Medical Art -> Vectors & Clipart

- readme.md
An image library specializing in science and nature images
Link: https://www.scienceimage.csiro.au
> scienceimage -> Stock Photos

- readme.md
A tool that takes two colors and shows a range of the midpoint colors between them
Link: https://meyerweb.com/eric/tools/color-blend
> [Color Blender] -> [Colors]

- readme.md
> remove duplicate

- readme.md
The documented collection of UI components using react
Link: https://uiplaybook.dev/
> [ui-playbook] -> [React UI]

- _config.yml
- readme.md
- Added New Section `Chrome Extensions` in the index and in the document, right before others section.
- Added some useful and Free Chrome Extensions:
- WhatFont: https://chrome.google.com/webstore/detail/whatfont/jabopobgcpjmedljpbcaablpmlmfcogm
- WhatRuns: https://chrome.google.com/webstore/detail/whatruns/cmkdbmfndkfgebldhnkbfhlneefdaaip?hl=en
- Web Developer: https://chrome.google.com/webstore/detail/web-developer/bfbameneiokkgbdmiekhjnmfkcnldhhm
- Awesome Screenshot: https://chrome.google.com/webstore/detail/awesome-screenshot-screen/nlipoenfbbikpbjkfpfillcgkoblgpmj?hl=en
- JSONView: https://chrome.google.com/webstore/detail/jsonview/chklaanhfefbnpoihckbnefhakgolnmc?hl=en
- Window Resizer: https://chrome.google.com/webstore/detail/window-resizer/kkelicaakdanhinjdeammmilcgefonfh?hl=en …
> Added Chrome Extensions section

- readme.md
A Hassle-Free Way to Self-Host Google Fonts
Link: https://google-webfonts-helper.herokuapp.com/fonts
> Google Webfonts Helper -> Fonts

- readme.md
Interactive animations in many formats like json,gif and mp4, libraries and plugins for Web & Mobile .
--
Link: https://lottiefiles.com/
> LottieFiles -> UI Components & Kits  

- readme.md
Open source web design debug tool built with JavaScript
Link: https://chrome.google.com/webstore/detail/visbug/cdockenadnadldjbbgcallicgledbeoc?hl=en
> VisBug -> Chrome Extensions

- readme.md
Quickly check and adjust contrast in realtime in your browser to meet WCAG 2.1 requirements
Link: https://chrome.google.com/webstore/detail/kontrast-wcag-contrast-ch/haphaaenepedkjngghandlmhfillnhjk?hl=en
> Kontrast -> Chrome Extensions

- readme.md
Adds a toolbar button with various web developer tools.
Link: https://chrome.google.com/webstore/detail/web-developer/bfbameneiokkgbdmiekhjnmfkcnldhhm
> Web Developer -> Chrome Extension

- readme.md
A small JS library to overlay images on top of the current page.
Link: https://lokeshdhakar.com/projects/lightbox2/
> Lightbox2 -> Javascript Animation Libraries

- readme.md
The site seems to no longer exist
> [Entypo]-> [Icons] No longer accessible

- readme.md
Zondicons is listed twice, so I removed one, now there is only one on line 201
> [Zondicons]->[Icons] Remove duplicate

- readme.md
PerfectPixel adds a semi-transparent image overlay over the top of the developed HTML to easily perform pixel perfect comparison between them, useful for replicating UI designs.
Link: https://chrome.google.com/webstore/detail/perfectpixel-by-welldonec/dkaagdgjmgdmbnecmcefdhjekcoceebi
> [PerfectPixel] -> [Chrome Extensions]

- readme.md
This extension inserts the Pesticide CSS into the current page, outlining each HTML element to better see placement on the page, very helpful for building layouts.
Link: https://chrome.google.com/webstore/detail/pesticide-for-chrome/bblbgcheenepgnnajgfpiicnbbdmmooh
> [Pesticide] -> [Chrome Extensions]

- readme.md
Fully responsive carousel
Link: https://kenwheeler.github.io/slick/
> Slick -> Javascript Animation Libraries

- readme.md
Link: https://metroui.org.ua/select.html
> [Metro 4] -> [CSS Frameworks]

- readme.md
Please remove duplicate
Please remove duplicate entry in [Chrome Extensions] list. The resource name "Web Developer" added twitch in "Chrome Extensions" list. (1st one at 3rd position and 2nd one at 13th position.)
Link: #
> [Web Developer] -> [Chrome Extensions] => Remove Duplicate

- readme.md
Using Font Awesome Free v5.13.0 icons to be converted into the hand-drawn effect of [RoughJS](https://roughjs.com/)
Link: https://github.com/djamshed/rough-awesome-font/
> [Rough Font Awesome] -> [Fonts]

- readme.md
> [ColorsWall] -> [Colors]

- readme.md
Unicons is a set of 1100+ Free line style icons available as SVG icons, Web fonts, and as components for JS frameworks like React, Vue and React Native.
Link: https://iconscout.com/unicons
> [Unicons] -> [Icon Fonts]

- readme.md
Collection of different Web and Mobile Designs
Link: https://www.designyourway.net/blog/web-and-mobile-design/
> Design your way -> Design Inspiration

- readme.md
Reveal the Vue plugins and technology stack powering any website or explore a database of 5500+ websites. Also available as a extension for Chrome and Firefox.
Link: https://vuetelemetry.com/
> [Vue Telemetry] -> [Others]

- readme.md
A must-have tool for designers and frontend developers to grab colors for any website.
Link: https://chrome.google.com/webstore/detail/site-palette/pekhihjiehdafocefoimckjpbkegknoh
> [Site Palette] -> [Chrome Extensions]

- readme.md
Test responsive web designs or mobile pages that detect specific user agents. Test multiple devices at the same time!
Link: https://chrome.google.com/webstore/detail/mobileresponsive-web-desi/elmekokodcohlommfikpmojheggnbelo
Advanced Eyedropper, Color Picker, Gradient Generator and other colorful goodies
Link: https://chrome.google.com/webstore/detail/colorzilla/bhlhnicpbhignbdhedgjhgdocnmhomnp
>  Chrome Extensions Update app config docs

- readme.md
Create and export CSS code for a custom box with an arrow extending out from the side. Great for tooltips, flyouts and the like.
Link: http://www.cssarrowplease.com/
> Update app config docs

- readme.md
Grid.js is a Free and open-source HTML table plugin written in TypeScript. It works with most JavaScript frameworks, including React, Angular, Vue and VanillaJs.
Link: https://gridjs.io/
> Grid.js - Advanced Table Plugin

- readme.md
A simple API to create user avatars from a user's name or email. Customize the color, font, size, and more.
Link: https://www.abstractapi.com/user-avatar-api
> Abstract User Avatar API -> ## UI Graphics

- readme.md
Downlode free PNG, SVG or AI file
Link: https://sketchvalley.com/
>  [sketchvalley] -> [UI Graphics]

- readme.md
barba.js is an easy-to-use library that helps you create fluid and smooth transitions between your website’s pages.
Link: https://barba.js.org/
> [barba.js] -> [Javascript Animation Libraries]

- readme.md
CSS Transitions and Transformations for Beginners
Link :https://thoughtbot.com/blog/transitions-and-transforms
> [Transitions and Transforms] -> [CSS Animation]

- readme.md
Mobirise Icons is a free, open source set of 150 elegant, pixel-perfect linear icons available as web icon font and SVG icons.
Link: https://mobiriseicons.com/
> [Mobirise Icons] -> [Icon Fonts]

- readme.md
Sass mixin library to build a website easily.
Link: https://gerillass.com/
> [Gerillass] -> [Others]

- readme.md
Sketchize is built for UI/UX Designers to help them design lovely apps for mobile, tablet, and desktop devices.
Link: https://www.sketchize.com/
> [Sketchize] -> [Others]

- readme.md
A lightweight Vue.js 3.x component for creating particles animations
Link: https://particles.matteobruni.it
> Particles.vue3 -> VueJS

- readme.md
Locomotive Scroll is a simple scroll library that provides detection of elements in viewport & smooth scrolling with parallax.
Link: https://locomotivemtl.github.io/locomotive-scroll/
> [Locomotive Scroll] -> [Javascript Animation Libraries]

- readme.md
DevDocs combines multiple API documentations in a fast, organized, and searchable interface.
Link: https://devdocs.io/
> devdocs -> others

- readme.md
Provides an elegant and quick way to create default text or generate Lorem Ipsum. Optimized for quick usage, but it can customized.
Link: https://chrome.google.com/webstore/detail/lorem-ipsum-generator-def/mcdcbjjoakogbcopinefncmkcamnfkdb?hl=en%20
Beautify CSS, JavaScript and JSON code when you open a .css/.js/.json file.
Link: https://chrome.google.com/webstore/detail/javascript-and-css-code-b/iiglodndmmefofehaibmaignglbpdald?hl=en
Find and download all images on a web page. With Imageye you can find, browse and download all the images present in a web page.
Link: https://chrome.google.com/webstore/detail/imageye-image-downloader/agionbommeaifngbhincahgmoflcikhm
> Chrome Extensions Update app config docs

- readme.md
Beautiful Tailwindcss components that support RTL languages & fully responsive based on Flexbox & CSS Grid.
Link: https://merakiui.com/
> [Meraki UI Components] -> [UI Components & Kits]

- readme.md
An HTML template generator using functional css.
Link: https://stitches.hyperyolo.com/
> [Stitches] -> [UI Components & Kits]

- readme.md
A free collection of Tailwindcss Templates - tailwind components for rapid UI development.
Link: https://tailwindtemplates.io/
> [Tailwind Templates] -> [UI Components & Kits]

- readme.md
A set of accessible and reusable prebuilt Tailwind components that are commonly used in web applications.
Link: https://kutty.netlify.app/
> [Kutty] -> [UI Components & Kits]

- readme.md
Components created using Tailwind CSS utilities class, so it can be customized to make themes easily.
Link: https://component.tailwindow.com/
> [Tailwindow] -> [UI Components & Kits]

- readme.md
CSSPortal is home to a large range of CSS generators, tools and resources.
Link: https://www.cssportal.com/
> [{CSS}Portal] -> [Others] Update config.

- readme.md
A zoomed eyedropper & color chooser tool that allows you to select color values from webpages and more. 
Link: https://chrome.google.com/webstore/detail/colorpick-eyedropper/ohcpnigalekghcmgcdcenkpelffpdolg
> [ColorPick Eyedropper] -> [Chrome Extensions]

- readme.md
Change the appearance of the web instantly.
Link: https://chrome.google.com/webstore/detail/stylebot/oiaejidbmkiecgbjeifoejpgmdaleoha
> [Stylebot] -> [Chrome Extensions]

- readme.md
Capture a screenshot of your current page in entirety and reliably—without requesting any extra permissions!
Link: https://chrome.google.com/webstore/detail/gofullpage-full-page-scre/fdpohaocaechififmbbbbbknoalclacl
> [GoFullPage] -> [Chrome Extensions]

- readme.md
The best resource for International Paper Sizes, Dimensions & Formats
Link: https://papersizes.io/
> [Papersizes] -> [Other]

- readme.md
React Developer Tools is a Chrome DevTools extension for the open-source React JavaScript library. It allows you to inspect the React component hierarchies in the Chrome Developer Tools. I think it's must be needed for the react developers.
Link: https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi
- [checked ] I have performed a self-review of submitted resource and its follows the guidelines of the project.
> [React Developer Tool] - [Chrome Extensions]

- readme.md
Compare your mockups with your live website to pinpoint any missing details.
Link: https://matchstick.xyz/
> [Match Stick] -> [Others]

- readme.md
is a free alternative for Font Awesome, flat icons that offer complete coverage of the main Font Awesome icon set. 
--
Link: https://icons8.com/line-awesome/
> [Line Awesome]-> Icons Fonts

- readme.md
Humans.fyi is a collection of brilliant personal websites filterable by colors and web technologies used in each website.
Link: https://humans.fyi/
> [Humans.fyi] -> [Design Inspiration]

- readme.md
> UPDATED readme.md

- readme.md
Link: https://www.fontget.com/
> [FontGet] -> [Fonts]

- readme.md
Daily.dev - A new tab Chrome extension which shows latest and greatest news about development 
Wappalyzer - A Chrome Extension that shows the technologies used on a website
Link - Daily.dev: https://daily.dev/
Link - Wappalyzer: https://www.wappalyzer.com/
> [daily.dev] -> [Chrome Extensions], [Wappalyzer] -> [Chrome Extensions]

- readme.md
Creative Commons, Stock Photos
A platform for searching images that can be reused. The images include licenses, author and whether the image can be used commercially.
The site is licensed under a Creative Commons Attribution 4.0 International license.
Link: https://search.creativecommons.org/
> Creative Commons -> Stock Photos

- readme.md
Link: https://www.splitshire.com/
> [SplitShire] -> [Stock Videos]

- readme.md
I have added new two resources in this repository which are W3css_templates, All-Free-Download
Link: https://www.w3schools.com/w3css/w3css_templates.asp
Link: https://all-free-download.com/free-website-templates/free-html-css-templates.html
> [W3css_templates, All-Free-Download] -> [HTML & CSS Templates]

- readme.md
SVG Artista is a useful tool to animate stroke and fill properties in SVG images with plain CSS code.
Link: https://svgartista.net/
> [SVG Artista] -> [CSS Animations]

- readme.md
Link:
- http://oocss.org/
- https://acss.io/
- http://getbem.com/
- http://smacss.com/
> Add CSS Methodologies section

- readme.md
Add the original color palette creating site Color Brewer. This is version 2, the revival. Scientifically based color palettes.
Link: https://colorbrewer2.org/
> [Color Brewer 2] -> [Colors]

- readme.md
SiteSee is a curated gallery of beautiful and modern websites.
Link: https://sitesee.co/
> [SiteSee] -> [Design Inspiration]

- readme.md
Free responsive jQuery carousel
Link: https://owlcarousel2.github.io/OwlCarousel2/
> [Owl carousel] -> [Javascript Animation Libraries]

- readme.md
Diagramming and visualization tools that allow creating databases, flowcharts, boards, floor-maps, and much more. 3 multi-page documents on the free tier
Link: https://lucid.app/pricing/lucidchart#/pricing
> [Lucidchart] -> [Online Design Tools]

- readme.md
IconSear.ch, LogoSear.ch and VectorLogoZone
My sites for SVG icons & logos
Links: 
https://iconsear.ch/ 
https://logosear.ch/  
https://www.vectorlogo.zone/
> Add IconSear.ch, LogoSear.ch and VectorLogoZone

- readme.md
Animate on Scroll Library
Link: https://github.com/michalsnik/aos
- [#] I have performed a self-review of submitted resource and its follows the guidelines of the project.
> [AOS] -> [CSS Animations]

- readme.md
Hero Patterns was repeated in the UI Graphics section, Removed its repeated instance
removed repeated instance of Hero Patterns in the table
Link: no new link added
Closes #657
> Fix -> UI Graphics

- readme.md
Hey @bradtraversy 
removing "Shade" as project doesn't seem to exist anymore.
Cheers!
> Removing "Shade"

- readme.md
Transform an SVG icon into multiple themes, and generate React icons，Vue icons，svg icons
Link: https://github.com/bytedance/IconPark
> IconPark -> Icons

- readme.md
Dimensions.com is an ongoing reference database of dimensioned drawings documenting the standard measurements and sizes of the everyday objects and spaces.
Link: https://www.dimensions.com/
> Dimensions -> UI Graphics

- readme.md
Blobmaker is a free generative design to help you quickly create random, unique, and organic-looking SVG shapes
Link: https://www.blobmaker.app/
> Blobmaker -> Online Design Tools

- readme.md
Link: http://flexboxfroggy.com/
> [flexboxfroggy] -> [Others]

- readme.md
Just added a new logos section with all the links and description at one place.
Link: https://github.com/bradtraversy/design-resources-for-developers
- [#] I have performed a self-review of submitted resource and its follows the guidelines of the project.
> Updated Readme.md for Logos

- readme.md
Mashup-Template
A few cool HTML5/CSS3 Templates you can use for free.
Link: http://www.mashup-template.com/templates.html
- [ x] I have performed a self-review of submitted resource and its follows the guidelines of the project.
> Mashup-Template => HTML5/CSS3 Templates

- readme.md
UI framework based on the veteran CSS framework foundation
Link: https://ngxfoundation.com/
> [NGX Foundation]-> [Angular UI]

- readme.md
Angular UI Platform focused on solving common enterprise needs
Link: https://teradata.github.io/covalent/v3/#/
> [Covalent UI]-> [Angular UI]

- readme.md
[Treact] -> [React UI Section]
Treact is a gallery of free and modern React templates and UI components developed using TailwindCSS as the front-end framework
Link: https://treact.owaiskhan.me/
> [Treact] -> [React UI Section]

- readme.md
CSS based Angular UI framework developed by VMware group
Link: https://clarity.design/
> [Clarity]-> [Angular UI]

- readme.md
Open is a free React template created for developers who want to create a quick and professional landing page for their open-source projects, online services, digital products, and more
Link: https://open.cruip.com/
> [Open] -> [React UI section]

- readme.md
[OAH-Admin]->[React UI section]
a free React admin dashboard template based on Gatsby with oah-ui components and elements package.
Link: https://gatsby-admin.paljs.com/extra-components/progress/
> [OAH-Admin]->[React UI section]

- readme.md
[carolina admin dashboard]->[React ui section]
free React admin template is powered by Material-UI components framework and features a clean and fresh design following Google's Material Design specifications.
Link: https://demo.uifort.com/carolina-react-admin-dashboard-material-ui-free-demo/LandingPage
> [carolina admin dashboard]->[React ui section]

- readme.md
[Tabler]->[React UI section]
Tabler is a free React admin dashboard template ideal for any kind of back-end web application.
Link: http://tabler-react.com/
> [Tabler]->[React UI section]

- readme.md
A crisp set of 15×15 icons designed by the Modulz team. All icons available as individual react component,SVG and more. 
Link: https://icons.modulz.app/
> [Radix Icons] -> [Icons]

- readme.md
SVG Wave is a tiny, free and beautiful SVG gradient waves generator for your UI or website desgin
Link: www.svgwave.in
> [SVG wave] -> [Vectors & Clipart]

- readme.md
Link: https://www.designbetter.co/books
> [Designbetter.co] -> [Others]

- readme.md
A resource that provides guidance for designing ethically humane digital products through patterns focused on user well-being.
Link: https://humanebydesign.com/
> [Humane By Design] -> [Design Systems & Style Guides]

- readme.md
Create and share beautiful images of your source code by typing or drop a file.
Link: https://carbon.now.sh
---
fix PR for #692 Resource add to list by @chuluq
> [Carbon] -> [Online Design Tools]

- readme.md
Removed duplicated React component library row.
Link: https://github.com/cruip/open-react-template/
> React -> Open

- readme.md
Provides a huge library of reusable UI Components for React, Angular, Vue, React Native. Also can be used for sharing UI Components among other team members.
Link: https://bit.dev/components
> Added Bit.

- readme.md
An open-source set of very general guidelines, inspired by Human Interface.
Link: https://guidelines.pr1mer.tech
> [Pr1mer's web guidelines] -> [Design Systems & Style Guides]

- readme.md
Absurd.design free illustrations.
Link: https://absurd.design/
> [Absurd.design] -> [UI Graphics]

- readme.md
Fixed some broken links in the table of contents and fixed the UI Graphics table which was not appearing correctly
> Fixed broken links + UI Graphics table

- readme.md
Fast, All-in-One Logo Generator
Link: https://www.namecheap.com/logo-maker/
> [Free Logo Maker] -> [Logos]

- readme.md
Hand-picked resources for web designers and developers, constantly updated.
Link: https://freebiesbug.com
Resource added by: @gxvr
> [Freebiesbug] -> [UI Graphics]

- readme.md
EOS Icons
EOS Icons is an open source iconic font used in SUSE products and other open source projects.
Link: https://icons.eosdesignsystem.com/
> [EOS Icons] - [Icons]

- readme.md
Link: https://www.heritagetype.com/collections/free-vintage-illustrations
Vintage Illustrations (vector and png)
> [Heritage Library] -> [Vectors & Clipart]

- readme.md
https://www.ffonts.net
Download stylish fonts for free and for personal use.
Link: www.ffonts.net
> FFonts - Fonts
