readme.md

https://phosphoricons.com
Phosphor is a flexible icon family for interfaces, diagrams, presentations — whatever, really.
Link: www.phosphoricons.com

[Phosphor Icons] -> [Icons]

---

readme.md

Its A Collection Of All Cheat Sheets.
Link: https://overapi.com/

[OverAPI] -> [Other]

---

readme.md

One new high-quality, open-source illustration each day.
Link: https://2.flexiple.com/scale/all-illustrations

[Flexiple] -> [UI Graphics]

---

readme.md

A web component for drawing patterns with CSS
Link: https://css-doodle.com/

[css-doodle] -> [CSS Frameworks]

---

readme.md

Another color palette generator
Link: https://farbvelo.elastiq.ch/

[FarbVelo] -> [Colors]

---

readme.md

TeenyIcons is a set of icons in SVG format easy to use in html 
Link: https://teenyicons.com/

[TeenyIcons] -> [Icons]

---

readme.md

Create badges with your own customization
Link: https://shields.io
reference: #722

[Shields] -> [Others]

---

readme.md

Lucide is an open-source icon library, a fork of Feather Icons.
Link: https://lucide.netlify.app/

[Lucide] -> [Icons]

---

readme.md

Icon Explorer with Instant searching, powered by Iconify.
Link: https://icones.js.org/

[Icones] -> [Icons]

---

readme.md

Random SVG Graphic Generator
Link: http://williamsharkey.com/Shapes.html

[williamsharkey] -> [Others]

---

readme.md

Download Malayalam fonts for free which are maintained by  Swathanthra Malayalam Computing(SMC)
Link: https://smc.org.in/fonts/

[Malayalam Fonts] -> [Fonts]

---

readme.md

AnimXYZ helps you create, customize, and compose animations for your website. Built for Vue, React, SCSS, and CSS.
Link: https://animxyz.com/

[AnimXYZ] -> [CSS Animations]

---

readme.md

Iconspedia is a website that contains a large collection of high quality free icons.
Link: https://www.iconspedia.com/

[Iconspedia] -> [Icons]

---

readme.md

Collection of free icons
Link: https://shittyicons.com/

[Shitty Icons] -> [Icons]

---

readme.md

Just practical Stunning Icons for everyone.
Link: [iconhub.io](https://iconhub.io/)

[iconhub] -> [Icons]

---

readme.md

find and use the coding fonts for free
Link: https://devfonts.gafi.dev/

[Dev Fonts] -> [Fonts]

---

readme.md

Remove Tagfold site

---

readme.md

Cool Text is a FREE graphics generator and have cool fonts for download
Cool Text is a FREE graphics generator for web pages and anywhere else you need an impressive logo without a lot of design work 
Link: www.cooltext.com

Add cooltext.com

---

readme.md

Illustration kit is a collection of open-source illustrations that is updated daily. 
Link: www.illustrationkit.com

Adds illustrationkit.com to ui graphics

---

readme.md

Swiper is the most modern free touch slider with hardware accelerated transitions and amazing native behavior. It supports VanillaJS and many frameworks like React, Vue, Angular etc. It is also open-source.
Link: https://swiperjs.com/

Swiperjs -> Javascript Animation Libraries

---

readme.md

An interactive list of Bootstrap classes, variables, and mixins. The only Bootstrap CheatSheet you will ever need.
Link: [https://bootstrap-cheatsheet.themeselection.com/](https://bootstrap-cheatsheet.themeselection.com/)

[Bootstrap CheatSheet] -> [Others]

---

readme.md

React components for easier customization and smooth development flow
Link: https://sha-el-design.netlify.app/  https://github.com/sha-el/sha-el-design

[Sha-el-design] -> [React UI]

---

readme.md

A minimal, almost class-less CSS library to write modern websites that look like LaTeX documents.
Link: https://latex.now.sh/

[latex.css] -> [CSS Frameworks]

---

readme.md

Add Paper CSS  CSS library for Front-end printing solution
Front-end printing solution
Link: https://github.com/cognitom/paper-css

 Resource -> CSS Framework 

---

readme.md

removed line 938
https://www.microcopyinspirations.com it's down. Not sure how long.

[Design Inspiration] -> [Microcopy Inspirations]

---

readme.md

Tabbied
Create and customize minimally generated patterns/artwork to use for background images, print and other projects.
https://tabbied.com/

[Tabbied] - [Vectors & Clip Art]

---

readme.md

`[Splide] -> [Javascript Animation Libraries]`
Splide is a free, pure JS library for carousels and sliders, which has a ton of features such as synchronized sliders, easy customization etc.
Link: https://splidejs.com/

[Splide] -> [Javascript Animation Libraries]

---

readme.md

The web editor is the tool that provides you with an enhanced way to inspect any website elements, alter their properties, insert contents, design, and visualize the way you want to see them.
Link: https://chrome.google.com/webstore/detail/web-editor/pdmlhckofhkhebmcplblcijijgjiakcm

[Web Editor] -> [Chrome Extensions]

---

readme.md

Fixed capitalization.
Made a proper sentence.
Removed duplicate of blobmaker.

Capitalization, Sentence, Duplicate

---

readme.md

Magnus UI is the ultimate UI framework that helps you in building consistent user interfaces effortlessly in react native.
Link: https://magnus-ui.com/

[Magnus UI] -> [React Native UI]

---

readme.md

Lightweight Mobile UI Components built on Vue.
Link: https://youzan.github.io/vant/

[Vant] -> [Vue UI]

---

readme.md

add Heikei on Vectors and Clipart

---

readme.md

React Native UI (RNUI) is a UI Toolset & Components Library for React Native from Wix
Link: https://wix.github.io/react-native-ui-lib/

[React Native UI Lib] -> [React Native UI]

---

readme.md

Open-source Vue 3 components system for your next project based on TypeScript
Link: https://quatrochan.github.io/Equal/

[Equal UI] -> [Vue UI]

---

readme.md

React Native Paper is a high-quality, standard-compliant Material Design library that has you covered in all major use-cases.
Link: https://reactnativepaper.com/

[React Native Paper] -> [React Native UI]

---

readme.md

UI Kitten is React Native framework for creating stunning cross-platform mobile applications. Design system based, brings your product from MVP to enterprise.
Link: https://akveo.github.io/react-native-ui-kitten/

[UI Kitten] -> [React Native UI]

---

readme.md

A simple online pattern generator to create repeatable SVG patterns. Perfect for website backgrounds, apparel, branding, packaging design and more.
Link: https://pattern.monster/

[Pattern Monster] -> [UI Graphics]

---

readme.md

Cross Platform React Native UI Toolkit that provides an all-in-one UI kit for creating apps in react native.
Link: https://reactnativeelements.com/

[React Native Elements] -> [React Native UI]

---

readme.md

Essential cross-platform UI components for React Native & Vue Native.
Link: https://nativebase.io/

[NativeBase] -> [React Native UI]

---

readme.md

Identify fonts from any website, bookmark, try, and buy them.
Link: https://chrome.google.com/webstore/detail/fonts-ninja/eljapbgkmlngdpckoiiibecpemleclhh

[Fonts Ninja] -> [Chrome Extension]

---

readme.md

Next generation compiler for Tailwind CSS
Link: https://windicss.org/

[Windi CSS] -> [CSS Frameworks]

---

readme.md

Mobile UI elements for Vue.js
Link: https://mint-ui.github.io/#!/en

[Mint UI] -> [Vue UI]

---

readme.md

Shoutem UI toolkit enables you to build professionally looking React Native apps with ease.
Link: https://shoutem.github.io/docs/ui-toolkit/introduction

[Shoutem UI] -> [React Native UI]

---

readme.md

A fantastic mobile ui lib implement by Vue.js
Link: https://didi.github.io/cube-ui/#/en-US

[Cube UI] -> [Vue UI]

---

readme.md

Free Avatar Library for Figma and Sketch
Link: https://themeselection.com/products/exemplar-free-avatar-library-for-figma-and-sketch/

[Exemplar] -> [UI Graphics]

---

readme.md

Based on the Vue 2.0 elegant Material Design UI component library
Link: https://muse-ui.org/#/en-US

[Muse UI] -> [Vue UI]

---

readme.md

AT-UI is a modular front-end UI framework for developing fast and powerful web interfaces based on Vue.js.
Link: https://at-ui.github.io/at-ui/#/en

[AT-UI] -> [Vue UI]

---

readme.md

A consistent and responsive Vue UI library, based on the front-end framework UIkit.
Link: https://vuikit.js.org/

[Vuikit] -> [Vue UI]

---

readme.md

It's appeared twice on README.md

Delete LINE Awesome redundency

---

readme.md

Instantly create mockups by adding a device frame to your videos.
Link: https://www.mock.video/

[Mock.Video] -> [Product & Image Mockups]

---

readme.md

Create product mockups with online mockup generator! Just choose a mockup, upload your design and download your image without a watermark.
Link: https://mockupbro.com/

[MockupBro] -> [Product & Image Mockups]

---

readme.md

A gorgeous CSS Framework for the web
Link: https://spiderpig86.github.io/Cirrus/

[Cirrus CSS] -> [CSS Frameworks]

---

readme.md

A Vue.js UI framework with only the bright side.
Link: https://antoniandre.github.io/wave-ui/

[Wave UI] -> [Vue UI]

---

readme.md

Use Tailwind CSS in React Native projects.
Link: https://github.com/vadimdemedes/tailwind-rn

[tailwind-rn] -> [React Native UI]

---

readme.md

An open-source UI component library inspired by Tailwind and AntDesign.
Supabase UI is a high-level UI component library with a focus on creating beautiful apps quickly and efficiently. Supabase UI is designed to be used with Tailwind CSS utlity classes.
Link: https://ui.supabase.io/

[Supabase UI] -> [React UI]

---

readme.md

A collection of JetBrains Web UI components.
Link: https://github.com/JetBrains/ring-ui

[Ring UI] -> [React UI]

---

readme.md

Set of Lightview and fully customizable Vue Components optimized for TailwindCSS
Link: https://www.vue-tailwind.com/

[VueTailwind] -> [Vue UI]

---

readme.md

Refreshed Windows 95 style UI components for your React app.
Link: https://react95.io/

[React95] -> [React UI]

---

readme.md

Reakit is a lower level component library for building accessible high level UI libraries, design systems and applications with React.
Link: https://reakit.io/

[Reakit] -> [React UI]

---

readme.md

A collection of essential UI components written with React.
Link: https://github.com/youzan/zent

[Zent] -> [React UI]

---

readme.md

An Ant design based configurable Mobile UI component library based on React Native.
Link: https://rn.mobile.ant.design/

[Ant Design Mobile RN] -> [React Native UI]

---

readme.md

Browse color palettes made by other designers, generate and submit your own
Link: https://verandacolor.com
- [ x] I have performed a self-review of submitted resource and its follows the guidelines of the project.

[Veranda Color] -> [Colors]

---

readme.md

A set of React UI components that supports Pinterest’s design language.
Link: https://github.com/pinterest/gestalt

[Gestalt] -> [React UI]

---

readme.md

Modern framework to print the web correctly.
Link: https://github.com/BafS/Gutenberg
**P.S.**
**Please take a look detail with this CSS library. I'm not really sure whether this "design" suitable in this list. Any objection or suggestion is opened**

[Gutenberg] -> [CSS Frameworks]

---

readme.md

World's smallest responsive fire css framework (395 bytes).
Link: https://github.com/ajusa/lit

[lit] -> [CSS Frameworks]

---

readme.md

Create color palettes from a single color
Link: https://www.paletter.app

Add Paletter to the list of color tools :)

---

readme.md

Arwes is a web framework to build user interfaces based on futuristic science fiction designs, animations, and sound effects.
Link: https://github.com/arwes/arwes

[Arwes] -> [CSS Frameworks]

---

readme.md

simpleParallax.js is a very simple and tiny Vanilla JS library that adds parallax animations on any images.
Link: https://simpleparallax.com/

add simpleparallax a tiny Vanilla JS library

---

readme.md

Bojler is an email framework for developing responsive and lightweight email templates that will render correctly across each of the most popular email clients.
Link: https://bojler.slicejack.com/
This is email template, but I take a look at the doc, and it provides some [component](https://bojler.slicejack.com/documentation/components/) class. Any suggestion or objection is welcomed. Thank you very much.

[Bojler] -> [CSS Frameworks]

---

readme.md

Primitive CSS Framework for dummies, without classes.
Link: https://github.com/yegor256/tacit

[Tacit] -> [CSS Frameworks]

---

readme.md

A CSS-in-JS framework built for React with props based utilities like display, fontSize or rotate.
Link: https://xstyled.dev/

[xstyled] -> [React UI]

---

readme.md

Oruga is a lightweight library of UI components for Vue.js without CSS framework dependency.
Link: https://oruga.io/

[Oruga] -> [Vue UI]

---

readme.md

QR Code Generator to easily create a QR code for your project.
Link: https://markodenic.com/tools/qr-code-generator/

QR Code Generator added

---

readme.md

eCommerce Website Design Gallery & Tech Inspiration.
Link: https://ecomm.design/

[ecomm.design] -> [Design Inspiration]

---

readme.md

A modern and minimal CSS framework for terminal lovers.
Link: https://terminalcss.xyz/

[Terminal CSS] -> [CSS Frameworks]

---

readme.md

A minimal classless css framework / theme.
Link: https://oxal.org/projects/sakura/

[Sakura] -> [CSS Frameworks]

---

readme.md

https://github.com/micah5/PSone.css
Link: PS1 style CSS Framework, inspired by NES.css.

[PSone] -> [CSS Frameworks]

---

readme.md

Marx is the classless CSS reset to be used in any projects (namely small ones).
Link: https://github.com/mblode/marx

[Marx] -> [CSS Frameworks]

---

readme.md

Style your webpage like Edward Tufte’s handouts.
Link: https://github.com/edwardtufte/tufte-css

[Tufte] -> [CSS Frameworks]

---

readme.md

BalmUI is a modular and customizable Material Design UI library for Vue.js.
Link: https://material.balmjs.com/#/

[BalmUI] -> [Vue UI]

---

readme.md

Iconoir is one of the biggest open source libraries with currently 914 SVG Icons. No premium icons, no email sign-up, no newsletters.
Link: https://iconoir.com/

[Iconoir] -> [Icons]

---

readme.md

A rich interaction, lightweight, high performance UI library based on Weex.
Link: https://github.com/apache/incubator-weex-ui

[Weex UI] -> [Vue UI]

---

readme.md

SnackUI is a UI Kit for React Native + react-native-web that's much faster rocket with an optimizing compiler.
Link: https://github.com/snackui/snackui

[SnackUI] -> [React Native UI]

---

readme.md

KUTE.js 
KUTE.js is a JavaScript animation engine for modern browsers.
Link: https://thednp.github.io/kute.js/

[KUTE.js] -> [JavaScript Animation]

---

readme.md

Create fluid and interactive gradient animations with this small javascript library
Link: https://sarcadass.github.io/granim.js/index.html

[Granim.js] -> [JavaScript Animation Libraries]

---

readme.md

Varlet is a Material design mobile component library developed based on Vue3, developed and maintained by partners in the community.
Link: https://github.com/haoziqaq/varlet

[Varlet] -> [Vue UI]

---

readme.md

Practice your HTML, CSS, and Javascript skills on real world design templates
Link: https://www.codewell.cc/

[Codewell] -> [Design Inspiration]

---

readme.md

React Rainbow is a collection of components that will reliably help you build your application in a snap. Give it a hack and let us know what you think.
Link: https://react-rainbow.io/

[React Rainbow] -> [React UI]

---

readme.md

Taiga UI is fully-treeshakable Angular UI Kit consisting of multiple base libraries and several add-ons.
Link: https://taiga-ui.dev/

[Taiga UI] -> [Angular UI]

---

readme.md

Moti is the universal animation package for React Native.
Link: https://moti.fyi/

[Moti] -> [React Native UI]

---

readme.md

The Biggest Paper Database with Sizes, Dimensions and Formats in Metric and Imperial units.
Link: https://papersdb.com/

[PapersDB] -> [Other]

---

readme.md

A free tool to create simple and complex CSS Gradients visually
Link: [https://colorgradient.dev](https://colorgradient.dev)

[ColorGradient] -> [Colors]

---

readme.md

A Vue 3 Component Library. Fairly Complete. Customizable Themes. Uses TypeScript. Not too Slow.
Link: https://www.naiveui.com/en-US/os-theme

[Naive UI] -> [Vue UI]

---

readme.md

Fix typo Choc UI

---

readme.md

Lighthouse is an open source automated tool for improving the performance and quality of your web pages/apps.
Link: https://chrome.google.com/webstore/detail/lighthouse/blipmdconlkpinefehnmjammfjpmpbjk

[Lighthouse] -> [Chrome Extensions]

---

readme.md

CSS loading animation with minimal effort!
Link: https://github.com/jh3y/whirl

[Whirl] -> [CSS Animation]

---

readme.md

Hamburgers is a collection of tasty CSS-animated hamburger icons. Also included is the source as a Sass library. It’s modular and customizable, so cook up your own hamburger.
Link: https://jonsuh.com/hamburgers/

[Hamburgers] -> [CSS Animations]

---

readme.md

Completely unstyled, fully accessible UI components, designed to integrate beautifully with Tailwind CSS.
Link: https://headlessui.dev/

[Headless UI] -> [UI Components & Kits]

---

readme.md

Create animated mockups in the browser 🔥.
Link: https://animockup.com

[Animockup] -> [Product Mockup]

---

readme.md

A showcase of awarding and showcasing the best websites, apps and games.
Link: www.designnominees.com

[Design Nominees] -> [Design Inspiration]

---

readme.md

Simple animation libraries for delightful user interfaces.
Link: https://popmotion.io/

[Popmotion] -> [JavaScript Animation Libraries]

---

readme.md

a curated list of free stock images, audio and videos.
Link: https://allthefreestock.com

[AllTheFreeStock] -> [Stock Photos]

---

readme.md

Vivus is a lightweight JavaScript class (with no dependencies) that allows you to animate SVGs, giving them the appearence of being drawn.
Link: https://maxwellito.github.io/vivus/

[Vivus] -> [JavaScript Animation Libraries]

---

readme.md

Free and Open Source UI Library for Vue 3 🤘.
Link: https://vuestic.dev

[Vuestic] -> [Vue UI]

---

readme.md

A JavaScript Typing Animation Library.
Link: https://mattboldt.com/demos/typed-js/

[Typed.js] -> [JavaScript Animation Libraries]

---

readme.md

Responsive and slick progress bars with animated SVG paths.
Link: https://kimmobrunfeldt.github.io/progressbar.js/

[Progress Bar.js] -> [JavaScript Animation]

---

readme.md

A React Component library for buliding modern applications easily & quickly.
Link: https://elementz.style

[Elementz] -> [React UI]

---

readme.md

Vue Final Modal is a tiny, renderless, mobile-friendly, feature-rich modal component for Vue.js.
Link: https://vue-final-modal.org

[Vue Final Modal] -> [Vue UI]

---

readme.md

Design inspiration from the best mobile app designs.
Link: https://foxyapps.co/

[Foxyapps] -> [Design Inspiration]

---

readme.md

SVG Vue/React components integrated from fluentui-system-icons, ionicons, etc. (Vue3, Vue2, React, SVG).
Link: https://www.xicons.org/#/

[Xicons] -> [Icons]

---

readme.md

Added styled components library to give readers a lib to create good UI Components.
Link: https://styled-components.com/

[Styled components]=>[UI Components & Kits]

---

readme.md

a service that allows developers & designers to create Mockups for their designs
Link: https://mediamodifier.com/

[Media modifier] -> [Product & Image Mockups]

---

readme.md

VEUI is an enterprise UI component library, based on Vue.js.
Link: https://veui.dev/en-US

[VEUI] -> [Vue UI]

---

readme.md

| Website&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; | Description |
| ----------------------- | ------------------ |
| [ChartJS](https://www.chartjs.org/)| Simple yet flexible JavaScript charting for designers & developers |
| [FrappeJS](https://frappe.io/charts)| Includes Green squares grid like in github, and other charts to use. |
| [G2Plot](https://g2plot.antv.vision/en)| G2Plot is an interactive and responsive charting library based on the grammar of graphics. |
| [Google Charts](https://developers.google.com/chart/)| Get the experience from google to create similar charts that google use. |
| [Data Driven Documents (D3)](https://d3js.org/)| bind complicated and massive data to interactive graphs. |

[ChartJS,FrappeJS,G2Plot,Google Charts,D3] -> [Javascript Chart Libraries]

---

readme.md

Duo is a collection of color combinations that I’ve curated from personal projects or that I’ve come across on the web.
Link: https://duo.alexpate.uk/

[Duo] -> [Colors]

---

readme.md

Design System For Vue Applications.
Link: https://github.com/Trendyol/grace

[Grace] -> [Vue UI]

---

readme.md

Browse UI patterns and component design ideas from real world products
Link: https://designvault.io/

[Design Vault] -> [Design Inspiration]

---

readme.md

Resource was already present; updated dead link
Link: https://lordicon.com/icons#free

[Lordicon] -> [Icons]

---

readme.md

Tailwind CSS Components
Link: https://daisyui.com/

[daisyUI] -> [UI Components & Kits]

---

readme.md

pixcleaner allows user to remove any background from pictures automatically and fast. Also provides an API for easy integration
Link: https://www.pixcleaner.com/

[pixcleaner.com] -> [Online Design Tools]

---

readme.md

A modern CSS UI library based on the glassmorphism design principles that will help you quickly design and build beautiful websites and applications.
Link: https://ui.glass/generator/

fix: add to Online design tools section ✅

---

readme.md

Screenlane is a website and newsletter that features the latest web and mobile design inspiration. 
> The concept caught on when UI Movement was launched on Product Hunt and was upvoted more than 1,000 times. It eventually grew to over 25,000 subscribers and thousands of visits per month. The simple newsletter website was eventually updated for easier browsing and filtering. Each new design was tagged so that you can easily find the most popular design animations for whatever design element you're interested in. In 2020 UI Movement needed to change. Based on my experience with UI Movement and realted site I run, I came up with the concept of what Screenlane is today.
https://screenlane.com/about/
Based on the description [here](https://screenlane.com/ui-movement/), I change the UI …

[Screenlane] -> [Design Inspiration]

---

readme.md

Free online platform for converting computer files to a variety of file formats
Link: https://www.vertopal.com

[Vertopal] -> [Others]

---

readme.md

[Figma Bootstrap 5 UI Kit] -> [UI Components & Kits]`
Figma Bootstrap UI Kit comprising 300+ organized Bootstrap 5 components built with atomic design system & auto layout. Kick start your next Figma project Just drag and drop pre-made components from the Assets panel. Configure them in the right sidebar. Fast and simple, as should be.
It is a comprehensive and easy-to-use Figma Library with organized components & atoms. It includes Bootstrap’s colors, grids, and typography so that you can easily customize it to fit your brand or product.
**Features:**
- Design and Dev Consistency 👨‍💻
- Effortless Resizing 😱
- Design with autolayout😍
- 300+ Organized Components 🛠
- Easy to customize
Link: https://drive.google.com/file/d/1SZOTxXYfCMujqP2P684Vd5QIrlk5bwe6/view?usp=sharing

Added Figma Bootstrap 5 UI Kit

---

readme.md

Fully configurable utility generator and CSS framework built entirely in Sass
Link: https://uniformcss.com

[Uniform CSS] -> [CSS Framework]

---

readme.md

Just fix some proper nouns
Link: No resources

Make some changes to proper nouns

---

readme.md

Landingfolio features the best landing page inspiration, templates, resources and examples on the web.
Link: https://landingfolio.com

[Landingfolio] -> [Design Inspiration]

---

readme.md

Glassmorphism is an incredible online tool for generating quick glassmorphic UI in CSS code snippets.
Link: https://glassmorphism.com/

[Glassmorphism] -> [Online Design Tools]

---

readme.md

Online tool to allows you to Minify & Beautify HTML/CSS/Javascript, Encode/Decode various formats, generate Fake dataset and many more features. With a delightful interface.
Link: https://smalldev.tools

[SmallDev.tools] -> [Others] 

---

readme.md

Free web tools for speed up your development
Link: https://angrytools.com/

[AngryTools] -> [Others]

---

readme.md

This resource was present but had a dead link. Removed from list.

LogoHub -> Removed dead link

---

readme.md

Table Convert Online is a web-based tool to converts Excel, URL, HTML, Markdown table and CSV to Markdown table, CSV/TSV, JSON, XML, YAML, insert SQL, HTML, Excel and LaTeX table.
Link: https://tableconvert.com/

[TableConvert] -> [Online Design Tools]

---

readme.md

Raster Simple Grid System is a Minimal and straight-forward CSS grid system utilizing descriptive HTML rather than semantic CSS.
Link: https://rsms.me/raster/

[RSMS] -> [CSS Frameworks]

---

.github/pull_request_template.md
readme.md

Modern & Interactive Open-source Charts
Link: https://apexcharts.com/

[ApexCharts.js] -> [Javascript Chart Libraries]

---

readme.md

Discover and connect to thousands of APIs
Link: https://rapidapi.com/hub

[Rapid API] -> [Others]

---

readme.md

`[Materio Vuetify Vuejs Admin Template] -> [Vue UI]`
**Materio VueJS Vuetify Admin Dashboard Template** – is the latest most developer-friendly 🤘🏻 & highly customizable✨ Admin Dashboard Template based on Vuetify. If you’re a developer looking for a Vuejs Admin Template enriched with features and a highly customizable look no further than Materio Free Vuetify Vuejs admin template🤩 . Besides, the highest industry standards are considered to bring you the very best Vuetify admin template that is not just fast🚀and easy to use, but highly scalable. Offering ultimate convenience and flexibility, you’ll be able to build whatever application you want without any hassle.
Furthermore, you can use this one of the best innovative free Vuejs admin templates to create eye-catching, high-quality, and …

Added Materio Vuetify Vuejs Admin Template

---

readme.md

Build smooth color schemes that flow from one color to another. Users van finetune hue, saturation value gradients of your palette and of each color swatch individually in a beautiful graphic way.
Link: [Palettte App](https://palettte.app)

Palettte App -> Colors

---

readme.md

Beautiful, fast and modern React UI library. |
Link: https://nextui.org/

[NextUI] -> [React UI]

---

readme.md

- Doodle Ipsum: The lorem ipsum of illustrations. Just customize your doodles, grab the code, and use them on your web prototypes, landing pages, or no-code tools.
- Figen: Post Cover & Background Generator Tool
Link: https://doodleipsum.com, Post Cover & Background Generator Tool

[Doodle Ipsum, Figen] -> [Online Design Tools]

---

readme.md

A tool to rapidly prototype and build stunning websites using Tailwind CSS
Link: https://www.devwares.com/windframe/

[Windframe] -> [Online design tools]

---

readme.md

Javascript chart libraries

---

readme.md

Consistency 'Table of Content' Naming

---

readme.md

Consistency Logos new line
Actually I'm working on this design-resources API, and this inconsistency makes reading the pattern of file quite hard. If you don't mind, maybe we could make more consistent format.

Consistency logos

---

readme.md

Vectors and clipart

---

readme.md

Fix React Native UI Libraries broken link at Table of Content

Consistency react native UI

---

readme.md

Consistency 'React UI Libraries' heading

---

readme.md

Consistency vue UI

---

readme.md

Consistency angular UI

---

readme.md

Consistency svelte UI

---

readme.md

Website with a lot of free, various design resources.
Link: https://uibundle.com

[UIBundle] -> [UI Graphics]

---

readme.md

Midnight.js lets you switch fixed headers on the fly
Link: https://aerolab.github.io/midnight.js/

Midnight js -> Javascript Animation Libraries

---

readme.md

React Provider Component to add a smooth scroll effect
Link: https://github.com/saidMounaim/React-Use-Smooth-Scroll

React Smooth Scroll -> React Ui

---

readme.md

Theatre.js is a JavaScript animation library with a GUI. It animates the DOM, WebGL, and any other JavaScript variable.
Link: https://www.theatrejs.com/

Theatre.js -> Javascript Animation Libraries

---

readme.md

This web app compresses JPEG files on client side, in the browser itself. It doesn't send them to a server for processing. Can process locally stored images, Google Photos or images saved on DropBox.
Link: https://watermarkly.com/compress-jpeg/

[Watermarkly] -> [Image Compression]

---

readme.md

Flowrift is a library made of beautifully designed Tailwind CSS UI blocks.
Link: https://flowrift.com/c/banner

Flowrift -> Css Library

---

readme.md

A new animation library, built on the Web Animations API for the smallest filesize and the fastest performance.
Link: https://motion.dev/

[Motion One] -> [CSS Animations]

---

readme.md

You may only need this tool for creating CSS gradient backgrounds and patterns.
Link: www.cssgradienteditor.com

[CSS Gradient Editor] -> [Colors]

---

readme.md

A comprehensive React UI components library based on the Arco Design system.
Link: https://arco.design/en-US

[Arco Design] -> [React UI Libraries]

---

readme.md

A modern, comprehensive, flexible design system that gives you all modular blocks you need to build sensible web apps & SaaS products. 
Link: https://semi.design/en-US

[Semi Design] -> [React UI Libraries]

---

readme.md

Brand Logos Free Download in SVG Vector & PNG File Format
Link: https://www.logo.wine/

[LOGOwine] -> [Logos]

---

readme.md

It allows you to quickly add and customize all the sections you need for your project's readme.
Link: https://readme.so

[Readme.so] -> [Others]

---

readme.md

A comprehensive Vue UI components library based on the Arco Design system.
Link: https://arco.design/vue/en-US/docs/start

[Arco Design Vue] -> [Vue UI Libraries]

---

readme.md

Convert any major image format into a highly optimized JPEG
Link: https://www.jpeg.io

[Jpeg.io] -> [Image Compression]

---

readme.md

Design tools that give you super powers. A collection of design tools that make you a super designer.
Link: https://superdesigner.co

[Superdesigner.co] -> [Design Inspiration]

---

readme.md

API for placeholder images but useful!
Link: https://lorem.space

[lorem.space] -> [Stock Photos]

---

readme.md

Beautifully crafted open source 3D icons. 100% FREE FOR COMMERCIAL AND PERSONAL USE UNDER CC0.
Link: https://3dicons.co

[3DICONS] -> [Icons]

---

readme.md

A free font collection website
Link: https://www.wfonts.com/

feat: wfonts font website

---

readme.md

Link: https://www.radix-ui.com/

[Radix UI] -> [React UI Libraries]

---

readme.md

Powerful cover image designer for your blog.
Link: [Slickr](https://slickr.vercel.app/)

[Slickr] - [Online Design Tools]

---

readme.md

Draw a favicon online and browse through a library of favicons made by other users
Link: [Favicon.cc](https://www.favicon.cc)

Favicon.cc -> Favicons

---

readme.md

Beautiful code screenshot generator.
Link: https://showcode.app

[Showcode] -> [Others]

---

readme.md

A website that presents various icons in different colors.
Link: [IconsDb](https://www.iconsdb.com/)

[ IconsDb ] -> [ Icons ]

---

readme.md

Atropos is a lightweight, free and open-source JavaScript library to create stunning touch-friendly 3D parallax hover effects.
Link: https://atroposjs.com/

[Atropos] -> [Javascript Animation Libraries]

---

readme.md

CSS shadow generator to create realistic shadows, developed by Josh W. Comeau.
Link: https://www.joshwcomeau.com/shadow-palette/

[Shadow Palette Generator] -> [Online Design Tools]

---

readme.md

Ray.so is an online tool to create beautiful images of code snippets.
Link: https://ray.so/

[Ray.so] -> [Online Design Tools]

---

readme.md

A tiny little drawing app.
Link: https://www.tldraw.com

[tldraw] -> [Others]

---

readme.md

Generate maskable PWA icons based on your existing icon.
Link: [https://maskable.app/editor/](https://maskable.app/editor/)

[Maskable.app] -> [Favicons]

---

readme.md

CSS Loaders & Spinners | CSS Animations
This is a library having a collection of different types of CSS loaders, spinners
Link: [https://cssloaders.github.io/](https://cssloaders.github.io/)

Add CSS Loaders & Spinners

---

readme.md

nice-waves
Beautiful animated waves
Link: https://gvguy.github.io/nice-waves/

[nice-waves] - [Javascript Animation Libraries]

---

readme.md

Pocoloco
Generate dynamic backgrounds for your website
Link: https://pocoloco.io/

[Pocoloco] - [CSS Animations]

---

readme.md

Halfmoon
Front-end framework with a built-in dark mode and full customizability using CSS variables; great for building dashboards and tools
Link: https://www.gethalfmoon.com/

[Halfmoon] -> [CSS Frameworks]

---

readme.md

Updated dead link to documentation page for resource.
Link: [Particles.vue](https://github.com/matteobruni/tsparticles/tree/main/components/vue)

Particles.vue -> Vue UI Libraries

---

readme.md

Updated dead link to documentation page for resource.
Link: [React tsParticles](https://github.com/matteobruni/tsparticles/tree/main/components/react)

React tsParticles -> React UI Libraries

---

readme.md

Updated dead link to documentation page for resource.
Link: [Svelte Particles](https://github.com/matteobruni/tsparticles/tree/main/components/svelte)

Svelte Particles -> Svelte UI Libraries

---

readme.md

Pico.css
Elegant styles for all natives HTML elements without .classes and dark mode automatically enabled.
Link: https://picocss.com/

[Pico.css] -> [CSS Frameworks]

---

readme.md

Updated dead link to documentation page for resource.
Link: [Particles.vue3](https://github.com/matteobruni/tsparticles/tree/main/components/vue3)

Particles.vue3 -> Vue UI Libraries

---

readme.md

PatternFly is an open source design system created to enable consistency and usability across a wide range of applications and use cases. PatternFly provides clear standards, guidance, and tools that help designers and developers work together more efficiently and build better user experiences. It is developed by Red Hat, Inc.
Link: [Patternfly](https://www.patternfly.org/)

[Patternfly] -> [Design Systems & Style Guides]

---

readme.md

A huge collection of Color Gradients displayed with eggs
Link: https://www.eggradients.com/

[Eggradients] -> [Colors]

---

readme.md

Super easy and lightweight css animation library.
Link: https://drawcall.github.io/AniX/

[AniX] -> [CSS Animations]

---

readme.md

Vizzu - a free, open-source Javascript library for building animated charts, data stories, and interactive explorers.
Link: https://lib.vizzuhq.com/0.3.0/

[Vizzu] -> [Javascript Chart Libraries]

---

readme.md

Delete duplicate entry of Halfmoon

[Duplicate] -> [Halfmoon] 

---

readme.md

Design Stripe
Create beautiful illustrations, no design skills needed.
Link: https://designstripe.com/catalog

[Design Stripe] -> [UI Graphics]

---

readme.md

Gradientos makes finding gradients easy. Just pick your colors and see the gradient live on a demo website on some common UI elements.
Link: https://www.gradientos.app

[Gradientos] -> [Colors]

---

readme.md

An enterprise-level design system jointly launched by the Bytedance GIP UED team and the architecture front-end team.
Link: https://arco.design/en-US

[Arco.design] -> [Design Systems & Style Guides]

---

readme.md

Fluid typography is a modern way of approaching responsive typography.
Link: https://modern-fluid-typography.vercel.app/

[Modern fluid typography editor] -> [Fonts]

---

readme.md

An SVG playground to share SVG stuff.
Link: https://holasvg.com/

[HOLA SVG] -> [UI Graphics]

---

readme.md

Website for referencing web colors. Color knowledge, Web colors, Hex color codes.
Link: https://encycolorpedia.com/

Encycolorpedia -> Colors

---

readme.md

Animated website backgrounds in a few lines of code.
Link: https://www.vantajs.com/

[Vanta.js] -> [Javascript Animation Libraries]

---

readme.md

Free templates, UI kits, icon, PSD
Link: https://symu.co/freebies/templates-4/

[symu.co] -> [UI Graphics]

---

readme.md

Link to resource was present, but redirected to a Twitter profile page.
Link: [FreebieSketch](http://freebiesketch.com/)

FreebieSketch -> UI Graphics

---

readme.md

Croma is easy to use color picker. It has options to pick color from image, generate color schemes and has a easy color picker.
Link: https://croma.app

[Colors] - [Add croma to color picker list]

---

readme.md

SVG Patterns
Link:  https://patterns.beaubus.com/

[BEAUBUS Patterns] -> [UI Graphics]

---

readme.md

Notiflix
JavaScript library for client-side non-blocking notifications, popup boxes, loading indicators, and more that makes your web projects much better.
Link: [https://notiflix.github.io/](https://notiflix.github.io/)

[Notiflix] -> [UI Components & Kits]

---

readme.md

devices.css
Pure CSS phones and tablets by Marvel App.
Link: http://marvelapp.github.io/devices.css/

[devices.css] -> [Others]

---

readme.md

Codepng allows you to create awesome snapshots from your source code that you can share on social media.
Link: https://www.codepng.app

[Codepng] -> [Online Design Tools]

---

readme.md

A pretty cool UI kit for Svelte.
Link: https://illright.github.io/attractions

[Attractions] -> [Svelte UI Libraries]

---

readme.md

A minimalistic UI/UX component library for Svelte and Sapper projects.
Link: https://docs.svelteit.dev

[Svelteit] -> [Svelte UI Libraries]

---

readme.md

Troopl is a free portfolio builder for web developers and data scientists. It helps people get a portfolio of work live on a customisable URL in minutes, instead of spending weeks building one from scratch. 
Link: www.troopl.com
- [ X ] I have performed a self-review of submitted resource and its follows the guidelines of the project.

[Troopl] -> [Other]

---

readme.md

Meshy (Mesh Gradient) is a tool to generate mesh gradients
Link: https://meshgradient.in

[Mesh Gradient] -> [UI Graphics]

---

readme.md

Open-source library of Tailwind CSS components
Link: flowbite.com
Free and open-source website themes, templates, and UI kits based on Bootstrap and React
Link: themesberg.com

Flowbite & Themesberg -> UI Components & Kits

---

readme.md

NextUI is a beautiful, fast and modern React UI library.
Link: https://nextui.org/

[NextUI] -> [React UI Libraries]

---

readme.md

Universal React design systems that optimize for native & web.  |
Link: https://tamagui.dev/

[Tamagui] -> [React Native UI Libraries]

---

readme.md

remove duplicate entry of NextUI

---

readme.md

Open-source & Easy to use Bootstrap 5 HTML Admin Template with Elegant Design & Unique Layout.
**Features:**
- Based on Bootstrap 5
- Vertical layout
- Dashboard
- 1 Chart library
- SASS Powered
- Authentication Pages
- Fully Responsive Layout
- Organized Folder Structure
- Clean & Commented Code
Link: https://github.com/themeselection/sneat-html-admin-template-free

Added Sneat Bootstrap 5 HTML Admin Template

---

readme.md

A tool for creating CSS Grid Layouts
Link: https://grid.layoutit.com/

[CSS Grid Generator] -> [Online Design Tools]

---

readme.md

Onlineboard is a free shareable whiteboard with real-time synchronization. It has dark mode, zoomable boards, multiple colors and export to image functionality. 
Link: www.onlineboard.eu

[Onlineboard] -> [Online Design Tools]

---

readme.md

Generate a pallet from one specified color
Link: [Color Designer](https://colordesigner.io/gradient-generator)

[Color Designer] -> [Colors]

---

readme.md

Bootstrap Admin Dashboard Template & UI Components Library
Link: https://coreui.io

CoreUI -> UI Components & Kits

---

readme.md

Mermaid is a Javascript based diagramming and charting tool that uses Markdown-inspired text definitions and a renderer to create and modify complex diagrams. The main purpose of Mermaid is to help documentation catch up with development.
Link: [https://github.com/mermaid-js/mermaid]

[Mermaid -> Online Design Tools]

---

readme.md

JsonT is a simple and powerful online JSON formatting tool.  You can format / save / share / transform/ edit and search JSON string conveniently. At the same time we keep it simple and concise, and we offer PWA so that you can use the tool without network just like a local software.
Link: [https://www.jsont.run](https://www.jsont.run/)
-  [x] I have performed a self-review of submitted resource and its follows the guidelines of the project.

[JSONT] -> [Online Design Tools]

---

readme.md

[Materio MUI React NextJS Admin Template] -> [React UI Libraries]`
Materio Free MUI React Next. js Admin Template is the most developer-friendly & highly customizable template based on [MUI](https://mui.com/)  & [ Next. js](https://nextjs.org/). Besides, it is available in both Typescript and JavaScript versions.
If you’re a developer looking for an MUI React Admin Template that is developer-friendly, rich with features, and highly customizable, look no further than Materio MUI React Next. js admin template. 
Link: https://github.com/themeselection/materio-mui-react-nextjs-admin-template-free

[Materio MUI React NextJS Admin Template] -> [React UI Libraries]

---

readme.md

Openverse is a search engine for catalog of CC images with layered filter.
Beta support for audio too.
Link: https://wordpress.org/openverse/

[Openverse] -> [Stock Photos]

---

readme.md

SVGR is an universal tool to transform a raw SVG into a ready-to-use React components.
Link: [react-svgr.com](https://react-svgr.com/)

[SVGR] -> [UI Components & Kits]

---

readme.md

AgnosticUI is a UI Component library that works in React, Vue 3, Svelte, and Angular
Link: http://agnosticui.com

[AgnosticUI] -> [UI Components & Kits]

---

readme.md

A 'naked' component library for building accessible, lightweight, on-brand applications.
Link: [vuetensils.stegosource.com](https://vuetensils.stegosource.com/)

[Vuetensils] -> [Vue UI Libraries]

---

readme.md

I added a website that hosts a collection of over 8000 free fonts and dingbats
Link: [https://www.urbanfonts.com/](https://www.urbanfonts.com/)

[UrbanFonts] -> [Fonts]

---

readme.md

Jitter is a online tool with which you can create motion graphics video
Link: [jitter.video](https://jitter.video)

[Jitter] -> [Online design tools]

---

.github/pull_request_template.md
readme.md

Draw perfect sine waves and export as SVG for your Front-End and design projects.
Link: https://www.sinwaver.com/

[SVG sine waves generator] -> [UI Graphics]

---

readme.md

A showcase of web typography designs with ready-to-use CSS codes.
Link: https://typespiration.com/

[Typespiration] -> [Fonts]

---

readme.md

free html templates
Link: www.htmlrev.com
- [ x ] I have performed a self-review of submitted resource and its follows the guidelines of the project.

[htmlrev] -> [Html & css]

---

readme.md

Added the ngx-admin in Angular UI Libraries
Link: https://akveo.github.io/ngx-admin/

[Ngx-admin] -> [Angular UI Libraries]

---

readme.md

Interactive interface design tool created by Facebook: For mac only
Link: www.origami.design

[Facebook's Origami] -> [Downloadable Design Software]

---

readme.md

[Free-Stock-Video] -> [Stock Videos]

---

readme.md

Hundreds Open-Source UI elements, made with HTML & CSS. Anyone can contribute. Includes buttons, checkboxes, spinners, cards, inputs and more.
Link: https://uiverse.io

uiverse > UI Components & Kits

---

readme.md

Penpot is the first Open Source design and prototyping platform meant for cross-domain teams. Non dependent on operating systems, Penpot is web based and works with open web standards (SVG). For all and empowered by the community.
Link to repo: https://github.com/penpot/penpot#what-is-penpot
Link to official website: https://penpot.app/

Penpot -> Online Design Tools

---

readme.md

A Svelte component library that implements the [Carbon Design System](https://www.carbondesignsystem.com/), an open source design system by IBM.
Link: https://carbon-components-svelte.onrender.com/

[Carbon Components Svelte] -> [Svelte UI Libraries]

---

readme.md

Generate gradients for your shadows with pure CSS. This generator makes it easy for you.
Link:  https://alvarotrigo.com/shadow-gradients/

Adding CSS shadows gradients generator

---

readme.md

A wide variety of snippet and article collections for CSS, JavaScript, Python and more.
Link: https://www.30secondsofcode.org/

`[30secondsofcode] -> [Others]`

---

readme.md

App to instantly generate browser mockups and beautiful screenshots for social media, blog posts and more. You can add gradient backgrounds, add browser frame, rounded corners and more.
Link: https://pika.style

[Pika] -> [Product & Image Mockups]

---

readme.md

Design web and mobile app mockups as quickly and easily as using PowerPoint. Visily's intuitive UI, built-in templates, and advanced AI help teams design stunning apps faster than ever.
Link: https://www.visily.ai/

[Visily] -> [Online Design Tools]

---

readme.md

The collection of 3300 emojis with their HTML codes for easy use.
Link: https://emojiguide.org/

[ Emoji Guide ] -> [Icons]

---

readme.md

Namecheap's official free logo maker tool for creating beautiful custom logos 
Link: https://www.namecheap.com/logo-maker/

[Namecheap Logo Maker] -> [Logos]

---

readme.md

Description: Royalty-free audio library for downloadable music and sound effects. Cleared for YouTube monetization.
Link: https://www.youtube.com/audiolibrary
- [ X] I have performed a self-review of submitted resource and its follows the guidelines of the project.

[YouTube Studio Audio Library] -> [Stock Music & Sound Effects]

---

readme.md

Apifox is like Postman + Swagger + Mock + JMeter 
Link:  https://apifox.cn

[Apifox] -> [Other]

---

readme.md

Splitting creates elements and adds CSS variables to unlock amazing possibilities for animating text, grids, and more!
Link: https://splitting.js.org/

[Splitting.js] -> [Javascript Animation Libraries]

---

readme.md

SVG random, cutely avatars collections
Link: https://boringavatars.com/

[Boring Avatars] -> [UI Graphics]

---

readme.md

A demonstration of what can be accomplished through CSS-based design. 
Link: http://csszengarden.com/

[CSS Zen Garden] -> [Design Inspiration]

---

readme.md

Online tool for extracting all images and SVGs of a website, all you need is just to drop the URL
Link: https://extract.pics/

[Image Extractor] -> [Other]

---

readme.md

Just-add-water CSS animations snippets 😜
Link: https://sarthology.github.io/Animatopy/

[Animatopy] -> [CSS Animations]

---

readme.md

Penpot is the first Open Source design and prototyping platform meant for cross-domain teams. Nondependent on operating systems, Penpot is web-based and works with open web standards (SVG). For all and empowered by the community.
Link: https://penpot.app/

[Penpot] -> [Online Design Tools]

---

readme.md

[BGjar] -> [Vectors & Clip Art]

---

readme.md

Adding the okso.app drawing app that has the possibility to organize sketches in the nested "drawing inside the drawing" structure
Link: https://okso.app

[okso.app] -> [Other] 

---

readme.md

Awesome website for all kinds of Moroccan vectors.
Link: [www.vector.ma](https://vector.ma/)

[Vector] -> [Vectors & Clip Art]

---

readme.md

Unique vector assets within seconds.
Link: https://app.heazy.studio/

[Heazy] -> [Vectors & Clip Art]

---

readme.md

Added a CSS Reset resource in the "Others" section which should help developers have a consistent baseline with their HTML elements.

Added Modern CSS Reset resource in readme.md

---

readme.md

Identify usability issues through a heuristic evaluation.
Link: hhttp://www.uxcheck.co/

[UX Check] -> [Chrome Extensions]

---

readme.md

Self-host Open Source fonts in neatly bundled NPM packages.
Link: [Fontsource](https://fontsource.org/)

[Fontsource] -> [Fonts]

---

readme.md

Ant Design Charts, a JS library to develop charts from dynamic data with excellent documentation.
Link: [linkToResource](https://charts.ant.design/en)

[AntV Charts] -> [Javascript Chart Library]

---

readme.md

I added Redux Developer Tool to the Chrome Extensions resource file
Link: www.linkToResource](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd?hl=en)

[Redux Developer Tool] -> [Chrome Extensions]

---

readme.md

Free open source Tailwind CSS components for marketing and e-commerce websites, as well as application UI.
Link: [www.linkToResource](https://www.hyperui.dev/)

[HyperUI] -> [UI Components & Kits]

---

readme.md

Tool for easily creating precise Calc() CSS functions
Link: https://fpece.com/calc-generator

[Calc Generator] -> [Online Design Tools]

---

readme.md

The website generate  beautifully curated selection of cool backgrounds that you can add to blogs, websites, or as desktop and phone wallpapers.
Edit this line with Small Description about new added resource
Link: www.linkToResource

add Cool Backgrounds Generator For CSS

---

readme.md

With that we can quickly generate color shades of our favorite colors or any colors, to create templates or CSS components with multiple color shades and more useful tools available on the same site
Link: [www.linkToResource](https://mdigi.tools/color-shades)

[Color Shades Generator] -> [Colors]

---

readme.md

update invalid URL of openby.design

---

readme.md

Patterns is a free resource on design patterns and component patterns for building powerful web apps with vanilla JavaScript and React.
Link: https://www.patterns.dev
- [ x] I have performed a self-review of submitted resource and its follows the guidelines of the project.

add patterns to design systems and style guides

---

readme.md

added resource https://www.setools.xyz/
Free tools website for developers
Link: https://www.setools.xyz/

[SETools.xyz] --> [Others]

---

readme.md

Find the best landing pages for your design inspiration based on your preference
Link: https://landings.dev

Landings -> Design Inspiration

---

readme.md

Yellow Lab Tools
Online test to help speeding up heavy web pages
Provide many hints for improvements.
Link: https://yellowlab.tools/
Signed-off-by: Pascal Brand <pascal.brand38@gmail.com>
- [X ] I have performed a self-review of submitted resource and its follows the guidelines of the project.

[Yellow Lab Tools] -> [Online Design Tools]

---

readme.md

Compress JPG and PNG images. No Limits. Bulk Conversion. Convert to WebP. Works Offline
Link: https://compressimage.io

[CompressImage.io] -> [Image Compression]

---

readme.md

Link: [https://www.fontbolt.com/](https://www.fontbolt.com/)

add fontbolt

---

readme.md

Clarify that Icons8 doesn't provide vector resources for free and that the upscaler is limited by the free tier.

[Icons8] -> [UI Graphics & Online Design Tools]

---

readme.md

React Resizable Panels: React components for resizable panel groups/layouts.
Link: https://github.com/bvaughn/react-resizable-panels

[React Resizable Panels] -> [React UI Libraries]

---

readme.md

**Hackertab**, a handy extension to help developers stay up-to-date with the latest tech happenings.
Link: [Extension](https://chrome.google.com/webstore/detail/hackertabdev-developer-ne/ocoipcahhaedjhnpoanfflhbdcpmalmp)

[Hackertab.dev] -> [Chrome Extensions]

---

readme.md

This is a React Library with components derived from the Carbon Design System by IBM.
There is also a tutorial to help get developers familiar with Carbon and React as a whole
Link: [https://carbondesignsystem.com/developing/frameworks/react/](https://carbondesignsystem.com/developing/frameworks/react/)

[Carbon React] -> [React UI Libraries]

---

readme.md

This is an open source CSS Framework, based on Material Design 3. Build Material Design interfaces in record time, without stress for devs 🍻. The first CSS Framework that implements Material Design 3.
Link: www.beercss.com

[BeerCSS] -> [CSS Frameworks]

---

readme.md

All-in-one free online file service, convert, edit and optimize your files.
Link: https://clipperly.com

[Clipperly] -> [Others]

---

readme.md

A free collection of Tailwind blocks & components
Link: https://wickedblocks.dev/

[UI Components & Kits] -> [Wicked Block]

---

readme.md

Mamba UI is a free, open-source collection of UI components and templates based on Tailwind CSS.
Link: https://mambaui.com/

[UI Components & Kits] -> [Mamba UI]

---

readme.md

100+ playful animated icons. Customize colours, stroke width, background and scale. Available in JSON and SVG format.
Link: https://unicornicons.com

Unicorn Icons -> Icons

---

readme.md

Simple online design tool for creating custom CSS scrollbars.
Link: [scrollbar.app](https://scrollbar.app)
- [ x ] I have performed a self-review of submitted resource and its follows the guidelines of the project.

[Scrollbar.app] -> [Online Design Tools]

---

readme.md

Trendiest open source Admin Template for React
Link: https://horizon-ui.com/

[Horizon-UI] -> [HTML & CSS Templates]

---

readme.md

Huemint uses machine learning to create unique color schemes for your brand, website, or graphic
Link: https://huemint.com/

[Huemint] -> [Colors]

---

readme.md

Bulk generate mockups from PSD templates by automatically placing images in SmartObjects. The visual editor allows you to change SmartObject parameters and see an updated mockup preview in realtime.
Link: [MockCity](https://mockcity.com/)

[MockCity] -> [Product & Image Mockups]

---

readme.md

Tons of components use with Tailwind CSS but write fewer class names greatly reducing tailwind's complexity for beginners . 
Link: https://daisyui.com/

[daisyUI] -> [CSS Frameworks]

---

readme.md

Get Thousands of Free High-Resolution Stock CC0 Photos
Link: https://isorepublic.com/

[ISO Republic] -> [Stock Photos]

---

readme.md

A library of React Hooks that provides accessible UI primitives for your design system.
Link: https://react-spectrum.adobe.com/react-aria/

[React Aria] -> [React UI Libraries]

---

readme.md

Fully responsive UI kits, built with Tailwind CSS.
Link: https://kitwind.io/products/kometa/components

[Kitwind] -> [UI Components & Kits]

---

readme.md

Free and Open-Source UI Components for Maximum Productivity.
Link: https://www.devui.io/

[DevUI] -> [UI Components & Kits]

---

readme.md

Tail-kit gives you access to over 250 free components and free templates, based on Tailwind CSS 3.0.
Link: https://www.tailwind-kit.com/

[Tail-Kit] -> [UI Components & Kits]

---

readme.md

An Open Source and free Svg Icon Library, it is a collection of your favorite icon libraries like Font Awesome, Material Icons, Hericons and Bootstrap Icons to provide you with a wide range of SVG icons to choose from.
Link:  https://react-icons.github.io/react-icons/

[React-Icons] -> [Icon Fonts]

---

readme.md

Just went through each Chrome extension to find the firefox equivalent if it existed
Links:
| Extension | Description |
| --------- | ----------- |
| [WhatFont](https://addons.mozilla.org/en-US/firefox/addon/zjm-whatfont/) | Identify fonts on web pages |
| [WhatRuns](https://addons.mozilla.org/en-US/firefox/addon/whatruns/) | Discover technologies used on websites |
| [Web Developer](https://addons.mozilla.org/en-US/firefox/addon/web-developer/) | Toolbar for web development tasks |
| [Awesome Screenshot & Screen Recorder](https://addons.mozilla.org/en-US/firefox/addon/screenshot-capture-annotate/) | Capture and annotate screenshots |
| [daily.dev - News for Busy Developers](https://addons.mozilla.org/en-US/firefox/addon/daily/) | Developer news and resources |
| …

FireFox Extensions -> New Section below Chrome Extensions

---

readme.md

Online Tailwind CSS color palette generator (the most accurate I've ever found).
You provide a color (usually your brand color), it finds the best shade for it and generates the rest of the palette (50:950).
Link: [uicolors.app/create](https://uicolors.app/create)

[Tailwind CSS Color Generator] -> [Colors]

---

readme.md

This resource allows users to easily copy Unicode characters and symbols, by simply left-clicking.
Link: https://unicopy.cc/

[Unicopy] -> [Icon Fonts]

---

.prettierignore
readme.md

Edit position of Description, add .prettierignore

fix desc position

---

readme.md

Sorry for the slow response time on the previous PR https://github.com/bradtraversy/design-resources-for-developers/pull/1268
Originally had it under Online Design Tools because that's where other speed tools like GTmetrix and Yellow Labs were, but moved to "Others" now

[DebugBear Speed Test] -> [Others]

---

readme.md

Pixel perfect mobile UI components built with Tailwind CSS
Link: https://konstaui.com/

[Konsta UI] -> [UI Components & Kit]

---

readme.md

UnoCSS is the instant atomic CSS engine, that is designed to be flexible and extensible. The core is un-opinionated, and all the CSS utilities are provided via presets.
Link: https://unocss.dev

Richardoey unocss

---

readme.md

A collection of 275+ open-source icons available for Figma, SVGs, and React.
Link: [sargamicons.com](https://sargamicons.com/)

[Sargam Icons] -> [Icons]

---

readme.md

Free Online Tools like Code Beautifiers, Code Formatters, Editors, Viewers, Minifier, Validators, Converters for Developers.
Link: https://codebeautify.org/

[Code Beautify] -> [Others]

---

readme.md

Fully styled and customizable components for Nuxt.
Link: [www.linkToResource](https://ui.nuxtlabs.com/getting-started)

[NuxtLabs UI] -> [Vue UI]

---

readme.md

Leonardo AI is an AI-powered design tool that can help you create designs based on reference images.
Link: https://leonardo.ai/
Checklist:
I have performed a self-review of submitted resource and its follows the guidelines of the project.
I got below picture with free tier. Maybe not the best because iIm still learning how to use the tools properly, maybe the prompt or model can be adjusted, but I think these pictures still can be design inspirations 😊
And [AI Graphic Design Tools] is a new section, please let me know if anyone has better naming 👍👍 Thank you~

[Leonardo.AI] -> [AI Graphic Design Tools]

---

readme.md

Expertly made, responsive, accessible components in React and HTML ready to be used on your website or app. Just copy and paste them on your Tailwind CSS project.
Link: https://wind-ui.com/

[Wind UI] -> [UI Components & Kits]

---

readme.md

An opinionated toast component for React.
Link: https://sonner.emilkowal.ski/

[Sonner] -> [UI Components]

---

readme.md

Logo category last resource is duplicate -Cheapname Logo Maker-
Link: www.namecheap.com/logo-maker/

Delete duplicated [Namecheap] -> [Logo]

---

readme.md

Nivo provides supercharged React components to easily build dataviz apps, it's built on top of d3. Also comes with server side rendering ability and fully declarative charts.
Link: https://nivo.rocks/
- [ x] I have performed a self-review of submitted resource and its follows the guidelines of the project.

`[Nivo]` -> `[Javascript Chart Libraries]`

---

readme.md

Added keenthemes
[KeenThemes] -> [HTML & CSS TEMPLATES]
Added KeenThemes to the list
Link: [KeenThemes](https://keenthemes.com/)

[KeenThemes] -> [HTML & CSS TEMPLATES]

---

readme.md

Neptune CSS is a lightweight CSS framework. Use it to develop your websites faster.
Link: [neptunecss.org](https://neptunecss.org/)

[Neptune CSS] -> [CSS Frameworks]

---

readme.md

A chat UI component that offers a ready-to-use chat interface with features like message bubbles, input toolbar, and more.
Link: https://github.com/FaridSafi/react-native-gifted-chat#readme

[React Native Gifted Chat] -> [UI Components & Kits]

---

readme.md

Page Collective is part of a network of design inspiration websites. |
Link: https://pagecollective.com/

[Page Collective] -> [Design Inspirations]

---

readme.md

Pines is a library of animations, sliders, tooltips, accordions, modals, and more! It's a set of UI elements that can be copy and pasted into any [Alpine](https://alpinejs.dev/) and [Tailwind](https://tailwindcss.com/) projects.
Link: https://devdojo.com/pines

[Pines] -> [UI Components & Kits]

---

readme.md

Skeleton is an open source UI toolkit built with Svelte + Tailwind that allows you to create reactive web interfaces using [Svelte](https://svelte.dev/) + [Tailwind CSS](https://tailwindcss.com/)
Link: https://www.skeleton.dev/

[Skeleton] -> [Svelte UI Libraries]

---

readme.md

[Echarts] -> [Javascript Chart Libraries]
An Open Source JavaScript Visualization Library with declarative syntax for Rapid Construction of a wide range  of Web-based Visualization charts
Link: [https://echarts.apache.org/en/index.html](https://echarts.apache.org/en/index.html)
- [ x ] I have performed a self-review of submitted resource and its follows the guidelines of the project.

add echarts library

---

readme.md

Fontshare is a free fonts service from the Indian Type Foundry (ITF), making quality fonts accessible to all.
Link: https://www.fontshare.com/

[Fontshare] -> [Fonts]

---

readme.md

Empower Your Web with Ultimate Performance and Flexibility
With Kuma UI's headless, zero-runtime UI components, build top-performing websites effortlessly, while enjoying the best developer experience. Say hello to the future of CSS-in-JS
Link: https://www.kuma-ui.com/

[Kuma UI] -> [UI Components & Kits]

---

readme.md

Compilation of free HTML5 Bootstrap templates from different categories
Link: [https://themewagon.com](https://themewagon.com/theme-price/free/)

[ThemeWagon] -> [HTML & CSS Templates]

---

readme.md

Unleash your creativity with out-of-this-world web design inspiration from across the web. |
Link: https://www.curated.design/

[Curated] -> [Design Inspiration]

---

readme.md

Bento Grids is a curated collection of tiles-based layouts that were popularized by Apple with their summary slides. |
Link: https://bentogrids.com/

[Bento Grids] -> [Design Inspiration]

---

.github/pull_request_template.md
readme.md

#Icon buddy
A collection of 100K+ open-source SVG icons, fully customizable for designers and developers.
Link: https://iconbuddy.app/

[Icon buddy] -> [Icons]

---

readme.md

Free graphic design software great to make mockups.
Link: (https://icons8.com/lunacy)

[Lunacy] -> [Mockups]

---

readme.md

Closes: #1349
Link: thepatternlibrary.com

Remove inactive resource

---

readme.md

https://favicon.inbrowser.app
* Tweak the settings and see preview in real time.
* Pure frontend. Everything is processed in browser. No privacy risk. Fast.
* Works without a network connection using PWA.
* Support all image formats supported by browser.
* `"purpose": "any"` and `"purpose": "maskable"` support.
* Outputs are losslessly minified using oxipng and svgo.
Link: https://favicon.inbrowser.app

[Favicon InBrowser.App] -> [Favicon]

---

readme.md

Hand—picked website and component inspiration library.
Link: https://a-fresh.website

[a-fresh.website] -> [Design inspiration]

---

readme.md

Formats and colors JSON content for better readability. It can also collapse and expand nested structures.
Link: [linkToResource](https://chrome.google.com/webstore/detail/json-formatter/bcjindcccaagfpapjjmafapmmgkkhgoa?hl=en)

[JSON Formatter] -> [Chrome Extension]

---

readme.md

A SEO tool that includes features like on-page SEO analysis, broken link checking, and SERP preview and more.
Link: [linkToResource](https://chrome.google.com/webstore/detail/seo-minion/giihipjfimkajhlcilipnjeohabimjhi?hl=en)

[SEO Minion] -> [Chrome Extension]

---

readme.md

GrapesJS is an open-source, multi-purpose, Web Builder Framework which combines different tools and features with the goal to help you (or users of your application) to build HTML templates without any knowledge of coding. It's a perfect solution to replace the common WYSIWYG editors, which are good for content editing but inappropriate for creating HTML structures.
Link: [grapesjs.com](https://grapesjs.com/)

[GrapesJS] -> [Online Design Tools]

---

readme.md

Creatica is a design tool to generate beautiful, unique SVG Backgrounds and patterns for websites.
Link: [Creatica](https://creatica.app/backgrounds/)

[Creatica] -> [UI Graphics]

---

readme.md

tsParticles v3 brought naming changes, updated the readme with the right urls and names
Link: https://particles.js.org

[tsParticles] -> [Javascript Animation Libraries] Updated tsParticles libraries

---

readme.md

StyleX combines the strengths and avoids the weaknesses of both inline styles and static CSS. Defining and using styles requires only local knowledge within a component, and avoids specificity issues while retaining features like Media Queries. StyleX builds optimized styles using collision-free atomic CSS which is superior to what could be authored and maintained by hand.
Link: https://stylexjs.com/

[StyleX CSS] -> [CSS Frameworks]

---

readme.md

React components to build charts and dashboards
Link: https://tremor.so/

Tremor → React UI Libraries

---

readme.md

ImgGen AI is a free AI image generator and enhancement tool
Link: [ImgGen.ai](https://imggen.ai)

ImgGen AI -> AI Graphic Design Tools

---

readme.md

This is a Medium article for learning design principles that every developer better knows With an explanation and link to full documentation.
Link: [Medium](https://medium.com/design-bootcamp/the-ultimate-design-principles-guide-for-developers-d4aa58937283)

[Design Principles For Developers] -> [Design Systems & Style Guides]

---

readme.md

Galileo AI is a UI generation platform for easy and fast design ideation. It allows users to generate interface designs from text.
Link: https://www.usegalileo.ai/

Galileo AI -> AI Graphic Design Tools

---

readme.md

A collection of awesome tools, resources and products for people who create and live on the internet.
Link: https://appydev.co/
> * [x]  I have performed a self-review of submitted resource and its follows the guidelines of the project.

[appydev] -> [Others]

---

readme.md

Preline UI is an open-source set of UI components and elements built with the world's fastest growing framework - Tailwind CSS.
Link: https://preline.co/index.html
> * [x]  I have performed a self-review of submitted resource and its follows the guidelines of the project.

[Preline UI] -> [UI Components & Kits]

---

readme.md

It is an interactive cheatsheet of Vue, Vue Router, and Pinia. The only Vue CheatSheet you will ever need whether you are using Vue, Vue Router & Pinia in your Vue project or starting a new Vue project.
It is aimed at a large community of Vue users who find it difficult to search for Vue, Vue Router, and Pinia.
**Features:**
- Comprehensive Coverage of Vue, Vue router, Pinia
- Interactive search
- Concise code snippet
- Easily copy code snippet, and use it
- Open source
Link: https://vue-cheatsheet.themeselection.com/

Added Vue CheatSheet

---

readme.md

Figpeek is a Figma and GitHub thumbnail generator. With Figpeek you can create and experiment your thumbnail with ease.
Link: https://figpeek.vercel.app/

[Figpeek] -> [Others]

---

readme.md

Update AntV website link

---

readme.md

CUBE is a simple and scalable CSS Methodology created by the wonderful [Andy Bell](https://piccalil.li/about).
He wrote an explanation article about it [here](https://piccalil.li/blog/cube-css).
Link: https://cube.fyi/

[CUBE] -> [CSS Methodologies]

---

readme.md

ScrewFast is an open-source template designed for quick and efficient web project setup, blending minimalism with functionality.
Link: https://github.com/mearashadowfax/ScrewFast
> * [x]  I have performed a self-review of submitted resource and its follows the guidelines of the project.

[ScrewFast] -> [HTML & CSS Templates]

---

readme.md

Update 404 `compat-table` url

---

readme.md

Free Incredible Animated Components.
Link: https://aceternity.sveltekit.io/
- [/] I have performed a self-review of submitted resource and its follows the guidelines of the project.

added Aceternity UI Svelte > Svelte UI Libraries

---

readme.md

Edit this line with Small Description about new added resource
Link: www.linkToResource

Removed Soft Components. Link is no longer valid.

---

readme.md

Svelte UX - Collection of Svelte components, actions, stores, and utilities to build highly interactive applications.
Link: 
[Svelte UX](https://svelte-ux.techniq.dev/)
Flowbite-Svelte - Flowbite-svelte is an open-source UI component library built with Svelte components, Tailwind CSS utility classes and based on the Flowbite design system.
Link: 
[Flowbite-Svelte](https://flowbite-svelte.com/)
- [/ ] I have performed a self-review of submitted resource and its follows the guidelines of the project.

Added Svelte UX & Flowbite Svelte - UI Svelte Libraries

---

readme.md

> Bits UI is a collection of headless component primitives that enable you to build your own custom components. They have been thoughtfully designed to prioritize simplicity without compromising customizability.
> 
> Under the hood, most of these components are powered by [Melt UI](https://melt-ui.com/), which provides an even lower-level builder API for creating headless components. Bits takes that API and wraps it in a more familiar component interface, allowing us to handle some quality of life improvements for you.
Link: https://www.bits-ui.com/docs/introduction

bits-ui -> Svelte UI Libraries

---

readme.md

Create semantic, responsive & accessible HTML tables to represent your tabular data. Set CSS properties, generate the code and copy & paste into your project.
Link: https://www.htmltables.io/
Checklist:

[HTML Table Generator] -> [UI Components & Kits]

---

readme.md

Prime vue address changed
link fix
Link: https://primevue.org/

Primve Vue -> Vue UI Libraries

---

readme.md

Removed Dead link https://www.codewell.cc

removed dead link from readme.md

---

readme.md

Link: https://ui.aceternity.com

[Aceternity UI] -> [React UI]

---

readme.md

Removed Uplabs, as the website is no longer available:
https://www.uplabs.com/

Removed broken link

---

readme.md

Top curated collective resources for elite designers.
Link: https://vectopus.com/
Checklist:

[Vectopus] -> [Icons]

---

readme.md

The world's biggest premium and free icon packs library of flat icons, line icons, filled outline, isometric and solid styles.
Link: https://roundicons.com/
Checklist:

[Round Icons] -> [Icons]

---

readme.md

Find code of beautifully designed web based components in HTML, CSS, JS and Tailwind, React, Framer motion..
Link: https://www.codeui.co.in/

[Code UI] -> [Web UI Components]

---

readme.md

Extendsclass
A collection of tools for developers: formatters, converters, playgrounds, API tools, and image tools.
Link: https://extendsclass.com/
- [c] I have performed a self-review of submitted resource and its follows the guidelines of the project.

[extendsclass] -> [Others]

---

readme.md

Free online JavaScript playground.
Link: https://runjs.app/play

[RunJS] -> [Others]

---

.github/pull_request_template.md
readme.md

Link: https://getcolorlab.com/
Colorlab is an online tool to create color palettes, gradients, color scales, check color contrast.
Link: www.getcolorlab.com

[Colorlab] -> [Colors]

---

readme.md

Deleted more inaccessible resources

Fixing broken and expired links

---

readme.md

Assorted resources for frontend developers and web designers.
Link: https://www.pillarstack.com/
- [ YES ] I have performed a self-review of submitted resource and its follows the guidelines of the project.

[Pillarstack] -> [Other]

---

readme.md

Free SVG image generator with different tools, waves, tiles, blobs, and others. 
Link: [Mossaik.app](https://www.mossaik.app/)

[Mossaik] -> [Vectors & Clip Art]

---

readme.md

A hand-curated collection of freeware, open-source, and public domain fonts intended for commercial use.
Link: https://justfreefonts.com/
- [*] I have performed a self-review of submitted resource and its follows the guidelines of the project.

[Just Free Fonts] -> [Fonts]

---

readme.md

Component Library for React
Link: [Edil Ozi](https://www.edilozi.pro/)
- [ yes] I have performed a self-review of submitted resource and its follows the guidelines of the project.

[Edil Ozi] -> [React Ui libraries]

---

readme.md

align table

---

readme.md

update with github repo link because broken link
Link: https://github.com/alyssaxuu/animockup

Update broken link - animockup

---

readme.md

Update broken link with github link
Link: https://github.com/rebassjs/rebass

update rebass link

---

readme.md

Description: Create custom accessible Tailwind-style color palettes, where you can modify HSL curves across whole swatches, check WCAG/APCA contrast, then export to Tailwind/CSS/Figma/Adobe (Disclaimer: I made this! Still need to add a favicon)
Link: https://www.inclusivecolors.com/

[InclusiveColors palette creator] -> [Colors]

---

readme.md

Update croma broken link and update the description. 
Link: https://chroma.dev/

update croma broken link

---

readme.md

`[Flyon UI Tailwind  CSS Components  Library] -> [UI Components & Kits]`
[FlyonUI](https://flyonui.com/) is the latest free Tailwind CSS Component Library. It is designed to combine the best of both worlds: the aesthetic appeal of semantic classes and the powerful functionality of JS plugins.
It has over 800+ components examples. Additionally, it uses the strength of DaisyUI & Preline.
Apart from that it is easy to use.
**Features:**
- 800+ free components examples
- Universal framework compatibility
- Unlimited themes
- Unstyled & Accessible Plugins
- Responsive & RTL support
- Free forever
- Beautiful and Semantic Styling
- Efficiency and Productivity
- Maintainable and Scalable
Check out the GitHub Repo as well: https://github.com/themeselection/flyonui
Link: https://flyonui.com/

Added Flyon UI Tailwind Component Library

---

readme.md

Cutting-edge tools powering Angular full-stack development.
Link: https://www.spartan.ng/

[Spartan] -> [Angular UI Libraries]

---

readme.md

Vue port of shadcn-ui
Link: https://www.shadcn-vue.com/

[shadcn-vue] -> [Vue UI Libraries

---

readme.md

Bestwebdesigntools
Curated selection of latest web design tools, agencies and landing page templates across the web.
Link: www.bestwebdesigntools.com

[bestwebdesigntools] -> [Design inspiration]

---

readme.md

Explore the best, hand-picked app motion design
Link: https://appmotion.design/

[App Motion] -> [Design Inspiration]

---

readme.md

Gradienty is an all-in-one toolkit for CSS & TailwindCSS developers. It has everything, from Glassmorphism, Animations, Text Gradients, Mesh Gradients, Box Shadow Gradients, Background Gradients to 16,000+ Color Palettes & even a Blob Generator.
Link: https://gradienty.codes
- [✔ ] I have performed a self-review of submitted resource and its follows the guidelines of the project.

[Gradienty] -> [CSS Animations]

---

readme.md

Unblurimage AI is 100% Free,No Sign-Up online tool for unblur image.
Link: https://unblurimage.ai/

[Unblurimage AI] -> [AI Graphic Design Tools] 

---

readme.md

_For #1460._
A Free tool to create beautiful mesh gradients only with CSS code. Use your own colors or randomly generated ones to build the trendiest CSS gradients.
Link: https://csshero.org/mesher

Added Mesher Tool by CSS Hero: CSS mesh gradients generator

---

readme.md

A curated gallery of professional website designs to inspire developers and designers seeking creative ideas and best practices.
Link: [www.linkToResource](https://websitevice.com/)

[ Design Inspiration ] -> [ Websitevice ]

---

readme.md

A visualization solution that includes visual charts, visual tables, and visual narrative syntax.
Link:
- VChart: https://visactor.io/vchart
- VTable: https://visactor.io/vtable
- VStory: https://visactor.io/vstory

[ Javascript Chart Libraries ] -> [ VChart & VTable & VStory ] 

---

readme.md

VMind is an intelligent visualization suite that offers smart interfaces powered by rule-based algorithms, machine learning, and large language models (LLMs).
Link:
- VMind: https://visactor.io/vmind

[ AI Graphic Design Tools ] -> [ VMind ]

---

readme.md

PNGFree.ai offers millions of high-quality free PNG images
Link: https://pngfree.ai

[Vectors & Clip Art] -> [PNGFree.ai]

---

readme.md

Effortless Shadcn UI Component Previews & Code Snippets
Link: https://www.shadcnui-blocks.com

[Shadcnui Blocks] - [UI Components & Kits]

---

readme.md

A collection of HTML, React, CSS and Tailwind CSS code snippets for buttons, box-shadows, cards, checkboxes, dropdowns and many more.
Link: https://cssnippets.shefali.dev/

[CSSnippets] -> [UI Components & Kits]

---

readme.md

Preview your theme changes across different components and layouts.
Link: https://shadcnstudio.com

Add shadcn studio

---

readme.md

HeroUI is the new name given to NextUI after rebranding. The former NextUI domain redirects to the current heroui.com
Link: https://www.heroui.com/

[Hero UI] -> [React UI Libraries]

---

readme.md

Generate pixel-perfect favicons for free in seconds
Link: [www.linkToResource](https://favifiles.com/)

Favicon Tool Added

---

readme.md

the domain were changed from edilozi.pro to [edil-ozi.pro](https://edil-ozi.pro)
Link: [link](https://edil-ozi.pro)
- [true] I have performed a self-review of submitted resource and its follows the guidelines of the project.

update domain name

---

readme.md

Free collection of Shadcn UI templates, components, blocks, boilerplates, and more.
Link: https://shadcntemplates.com

[Shadcn Templates] > [React UI Libraries]

---

readme.md

Brand new uncommon components for your Next.js project. Use with ease through shadcn CLI 3.0
Link: https://skiper-ui.com

[Skiper UI] > [React UI Libraries]
